<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MasterOpdTableSeeder extends Seeder
{
    public function run()
    {
        \DB::table('master_opd')->delete();

        $data = [
            ['nama_opd' => 'DINAS KOMUNIKASI DAN INFORMATIKA',                                    'alias_opd' => 'DISKOMINFO',          'order' => 1],
            ['nama_opd' => 'BADAN KEPEGAWAIAN DAN PENGEMBANGAN SUMBER DAYA MANUSIA',               'alias_opd' => 'BKPSDM',              'order' => 2],
            ['nama_opd' => 'INSPEKTORAT',                                                           'alias_opd' => 'INSPEKTORAT',         'order' => 3],
            ['nama_opd' => 'BADAN KEUANGAN DAERAH',                                                  'alias_opd' => 'BKD',                 'order' => 4],
            ['nama_opd' => 'BADAN PERENCANAAN PEMBANGUNAN DAERAH',                                  'alias_opd' => 'BAPPEDA',             'order' => 5],
            ['nama_opd' => 'SATUAN POLISI PAMONG PRAJA DAN PEMADAM KEBAKARAN',                     'alias_opd' => 'SATPOL PP',           'order' => 6],
            ['nama_opd' => 'BADAN KESATUAN BANGSA DAN POLITIK',                                    'alias_opd' => 'KESBANGPOL',          'order' => 7],
            ['nama_opd' => 'DINAS PEMBERDAYAAN PEREMPUAN PERLINDUNGAN PENGENDALIAN PENDUDUK DAN KELUARGA BERENCANA', 'alias_opd' => 'DP3AP2KB',         'order' => 8],
            ['nama_opd' => 'SEKRETARIAT DAERAH',                                                    'alias_opd' => 'SETDA',               'order' => 9],
            ['nama_opd' => 'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU',               'alias_opd' => 'DPMPTSP',             'order' => 10],
            ['nama_opd' => 'SEKRETARIAT DPRD',                                                      'alias_opd' => 'SETWAN',              'order' => 11],
            ['nama_opd' => 'DINAS PEKERJAAN UMUM DAN PENATAAN RUANG',                              'alias_opd' => 'PUPR',                'order' => 12],
            ['nama_opd' => 'DINAS PEMBERDAYAAN MASYARAKAT',                                        'alias_opd' => 'DPM',                 'order' => 13],
            ['nama_opd' => 'DINAS KESEHATAN',                                                       'alias_opd' => 'DINKES',              'order' => 14],
            ['nama_opd' => 'DINAS SOSIAL',                                                          'alias_opd' => 'DINSOS',              'order' => 15],
            ['nama_opd' => 'DINAS PENDIDIKAN',                                                      'alias_opd' => 'DISDIK',              'order' => 16],
            ['nama_opd' => 'DINAS PERPUSTAKAAN DAN KEARSIPAN',                                     'alias_opd' => 'DISPUSIP',            'order' => 17],
            ['nama_opd' => 'DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL',                             'alias_opd' => 'DISDUKCAPIL',         'order' => 18],
            ['nama_opd' => 'DINAS PERTANIAN',                                                       'alias_opd' => 'DISTAN',              'order' => 19],
            ['nama_opd' => 'DINAS KOPERASI UKM, PERDAGANGAN DAN TENAGA KERJA',                    'alias_opd' => 'DISKOPDAGNAKER',      'order' => 20],
            ['nama_opd' => 'DINAS PARIWISATA, PEMUDA, OLAHRAGA DAN KEBUDAYAAN',                   'alias_opd' => 'DISPARPORABUD',       'order' => 21],
            ['nama_opd' => 'DINAS PERUMAHAN RAKYAT DAN KAWASAN PEMUKIMAN, PERHUBUNGAN DAN LINGKUNGAN HIDUP', 'alias_opd' => 'DISPERKIMHUBLH', 'order' => 22],
            ['nama_opd' => 'DINAS PERIKANAN DAN PANGAN',                                           'alias_opd' => 'DISKANPANG',          'order' => 23],
            ['nama_opd' => 'BADAN PENANGGULANGAN BENCANA DAERAH',                                 'alias_opd' => 'BPBD',                'order' => 24],
            ['nama_opd' => 'RSUD TUANKU RAO',                                                       'alias_opd' => 'RSUD T. RAO',         'order' => 25],
            ['nama_opd' => 'RSUD TUANKU IMAM BONJOL',                                               'alias_opd' => 'RSUD T. BONJOL',      'order' => 26],
            ['nama_opd' => 'KECAMATAN LUBUK SIKAPING',                                              'alias_opd' => 'KEC. LUBUK SIKAPING', 'order' => 27],
            ['nama_opd' => 'KECAMATAN SIMPATI',                                                     'alias_opd' => 'KEC. SIMPATI',        'order' => 28],
            ['nama_opd' => 'KECAMATAN BONJOL',                                                      'alias_opd' => 'KEC. BONJOL',         'order' => 29],
            ['nama_opd' => 'KECAMATAN DUA KOTO',                                                    'alias_opd' => 'KEC. DUA KOTO',       'order' => 30],
            ['nama_opd' => 'KECAMATAN PANTI',                                                       'alias_opd' => 'KEC. PANTI',          'order' => 31],
            ['nama_opd' => 'KECAMATAN MAPAT TUNGGUL',                                               'alias_opd' => 'KEC. MAPAT TUNGGUL',  'order' => 32],
            ['nama_opd' => 'KECAMATAN MAPAT TUNGGUL SELATAN',                                       'alias_opd' => 'KEC. MAPAT TUNGGUL SEL', 'order' => 33],
            ['nama_opd' => 'KECAMATAN PADANG GELUGUR',                                              'alias_opd' => 'KEC. PADANG GELUGUR', 'order' => 34],
            ['nama_opd' => 'KECAMATAN RAO',                                                         'alias_opd' => 'KEC. RAO',            'order' => 35],
            ['nama_opd' => 'KECAMATAN RAO SELATAN',                                                 'alias_opd' => 'KEC. RAO SELATAN',    'order' => 36],
            ['nama_opd' => 'KECAMATAN RAO UTARA',                                                   'alias_opd' => 'KEC. RAO UTARA',      'order' => 37],
            ['nama_opd' => 'KECAMATAN TIGO NAGARI',                                                 'alias_opd' => 'KEC. TIGO NAGARI',    'order' => 38],
            ['nama_opd' => 'PUSKESMAS CUBADAK',                                                     'alias_opd' => 'PKM CUBADAK',         'order' => 39],
            ['nama_opd' => 'PUSKESMAS SIMPANG TONANG',                                             'alias_opd' => 'PKM SIMPANG TONANG',  'order' => 40],
            ['nama_opd' => 'PUSKESMAS BONJOL',                                                      'alias_opd' => 'PKM BONJOL',          'order' => 41],
            ['nama_opd' => 'PUSKESMAS SIMPATI',                                                     'alias_opd' => 'PKM SIMPATI',         'order' => 42],
            ['nama_opd' => 'PUSKESMAS PEGANG BARU',                                                 'alias_opd' => 'PKM PEGANG BARU',     'order' => 43],
            ['nama_opd' => 'PUSKESMAS LADANG PANJANG',                                             'alias_opd' => 'PKM LADANG PANJANG',  'order' => 44],
            ['nama_opd' => 'PUSKESMAS KUMPULAN',                                                    'alias_opd' => 'PKM KUMPULAN',        'order' => 45],
            ['nama_opd' => 'PUSKESMAS LANSAT KADAP',                                                'alias_opd' => 'PKM LANSAT KADAP',    'order' => 46],
            ['nama_opd' => 'PUSKESMAS SILAYANG',                                                    'alias_opd' => 'PKM SILAYANG',        'order' => 47],
            ['nama_opd' => 'PUSKESMAS TAPUS',                                                       'alias_opd' => 'PKM TAPUS',           'order' => 48],
            ['nama_opd' => 'PUSKESMAS RAO',                                                         'alias_opd' => 'PKM RAO',             'order' => 49],
            ['nama_opd' => 'PUSKESMAS PINTU PADANG',                                                'alias_opd' => 'PKM PINTU PADANG',    'order' => 50],
            ['nama_opd' => 'PUSKESMAS KOTO RAJO',                                                   'alias_opd' => 'PKM KOTO RAJO',       'order' => 51],
            ['nama_opd' => 'PUSKESMAS KUAMANG',                                                     'alias_opd' => 'PKM KUAMANG',         'order' => 52],
            ['nama_opd' => 'PUSKESMAS LUBUK SIKAPING',                                             'alias_opd' => 'PKM LUBUK SIKAPING',  'order' => 53],
            ['nama_opd' => 'PUSKESMAS SUNDATAR',                                                    'alias_opd' => 'PKM SUNDATAR',        'order' => 54],
            ['nama_opd' => 'NAGARI MALAMPAH',                                                       'alias_opd' => 'NAG. MALAMPAH',       'order' => 55],
            ['nama_opd' => 'NAGARI MALAMPAH BARAT',                                                 'alias_opd' => 'NAG. MALAMPAH BARAT', 'order' => 56],
            ['nama_opd' => 'NAGARI LADANG PANJANG',                                                 'alias_opd' => 'NAG. LADANG PANJANG', 'order' => 57],
            ['nama_opd' => 'NAGARI LADANG PANJANG BARAT',                                           'alias_opd' => 'NAG. LADANG PANJANG BAR', 'order' => 58],
            ['nama_opd' => 'NAGARI BINJAI',                                                         'alias_opd' => 'NAG. BINJAI',         'order' => 59],
            ['nama_opd' => 'NAGARI SIMPANG',                                                        'alias_opd' => 'NAG. SIMPANG',        'order' => 60],
            ['nama_opd' => 'NAGARI SIMPANG UTARA',                                                   'alias_opd' => 'NAG. SIMPANG UTARA',  'order' => 61],
            ['nama_opd' => 'NAGARI ALAHAN MATI',                                                    'alias_opd' => 'NAG. ALAHAN MATI',    'order' => 62],
            ['nama_opd' => 'NAGARI ALAHAN MATI HILIA',                                              'alias_opd' => 'NAG. ALAHAN MATI HILIA', 'order' => 63],
            ['nama_opd' => 'NAGARI LIMO KOTO',                                                      'alias_opd' => 'NAG. LIMO KOTO',      'order' => 64],
            ['nama_opd' => 'NAGARI KOTO KACIAK',                                                    'alias_opd' => 'NAG. KOTO KACIAK',    'order' => 65],
            ['nama_opd' => 'NAGARI KOTO KACIAK BARAT',                                              'alias_opd' => 'NAG. KOTO KACIAK BAR', 'order' => 66],
            ['nama_opd' => 'NAGARI GANGGO HILIA',                                                   'alias_opd' => 'NAG. GANGGO HILIA',   'order' => 67],
            ['nama_opd' => 'NAGARI GANGGO MUDIAK',                                                  'alias_opd' => 'NAG. GANGGO MUDIAK',  'order' => 68],
            ['nama_opd' => 'NAGARI TANJUANG BERINGIN',                                             'alias_opd' => 'NAG. TANJUANG BERINGIN', 'order' => 69],
            ['nama_opd' => 'NAGARI TANJUANG BERINGIN UTARA',                                       'alias_opd' => 'NAG. TANJUANG BERINGIN UT', 'order' => 70],
            ['nama_opd' => 'NAGARI TANJUANG BERINGIN SELATAN',                                    'alias_opd' => 'NAG. TANJUANG BERINGIN SEL', 'order' => 71],
            ['nama_opd' => 'NAGARI JAMBAK',                                                         'alias_opd' => 'NAG. JAMBAK',         'order' => 72],
            ['nama_opd' => 'NAGARI DURIAN TINGGI',                                                  'alias_opd' => 'NAG. DURIAN TINGGI',   'order' => 73],
            ['nama_opd' => 'NAGARI PAUH',                                                           'alias_opd' => 'NAG. PAUH',           'order' => 74],
            ['nama_opd' => 'NAGARI AIA MANGGIH',                                                    'alias_opd' => 'NAG. AIA MANGGIH',    'order' => 75],
            ['nama_opd' => 'NAGARI AIA MANGGIH UTARA',                                              'alias_opd' => 'NAG. AIA MANGGIH UTARA', 'order' => 76],
            ['nama_opd' => 'NAGARI AIA MANGGIH SELATAN',                                           'alias_opd' => 'NAG. AIA MANGGIH SEL', 'order' => 77],
            ['nama_opd' => 'NAGARI AIA MANGGIH BARAT',                                             'alias_opd' => 'NAG. AIA MANGGIH BARAT', 'order' => 78],
            ['nama_opd' => 'NAGARI SUNDATA',                                                        'alias_opd' => 'NAG. SUNDATA',         'order' => 79],
            ['nama_opd' => 'NAGARI SUNDATA UTARA',                                                  'alias_opd' => 'NAG. SUNDATA UTARA',   'order' => 80],
            ['nama_opd' => 'NAGARI SUNDATA SELATAN',                                                'alias_opd' => 'NAG. SUNDATA SEL',     'order' => 81],
            ['nama_opd' => 'NAGARI PANTI',                                                          'alias_opd' => 'NAG. PANTI',           'order' => 82],
            ['nama_opd' => 'NAGARI PANTI UTARA',                                                    'alias_opd' => 'NAG. PANTI UTARA',     'order' => 83],
            ['nama_opd' => 'NAGARI PANTI TIMUR',                                                    'alias_opd' => 'NAG. PANTI TIMUR',     'order' => 84],
            ['nama_opd' => 'NAGARI PANTI SELATAN',                                                  'alias_opd' => 'NAG. PANTI SEL',       'order' => 85],
            ['nama_opd' => 'NAGARI PADANG GELUGUR',                                                 'alias_opd' => 'NAG. PADANG GELUGUR',  'order' => 86],
            ['nama_opd' => 'NAGARI SITOMBOL',                                                       'alias_opd' => 'NAG. SITOMBOL',        'order' => 87],
            ['nama_opd' => 'NAGARI BAHAGIA',                                                        'alias_opd' => 'NAG. BAHAGIA',         'order' => 88],
            ['nama_opd' => 'NAGARI SONTANG CUBADAK',                                                'alias_opd' => 'NAG. SONTANG CUBADAK', 'order' => 89],
            ['nama_opd' => 'NAGARI SIMPANG TONANG',                                                 'alias_opd' => 'NAG. SIMPANG TONANG',  'order' => 90],
            ['nama_opd' => 'NAGARI SIMPANG TONANG UTARA',                                           'alias_opd' => 'NAG. SIMPANG TONANG UT', 'order' => 91],
            ['nama_opd' => 'NAGARI SIMPANG TONANG SELATAN',                                        'alias_opd' => 'NAG. SIMPANG TONANG SEL', 'order' => 92],
            ['nama_opd' => 'NAGARI CUBADAK',                                                        'alias_opd' => 'NAG. CUBADAK',         'order' => 93],
            ['nama_opd' => 'NAGARI CUBADAK TIMUR',                                                  'alias_opd' => 'NAG. CUBADAK TIMUR',   'order' => 94],
            ['nama_opd' => 'NAGARI CUBADAK TENGAH',                                                 'alias_opd' => 'NAG. CUBADAK TENGAH',  'order' => 95],
            ['nama_opd' => 'NAGARI CUBADAK BARAT',                                                  'alias_opd' => 'NAG. CUBADAK BARAT',   'order' => 96],
            ['nama_opd' => 'NAGARI PADANG MENTINGGI',                                              'alias_opd' => 'NAG. PADANG MENTINGGI', 'order' => 97],
            ['nama_opd' => 'NAGARI PADANG MENTINGGI UTARA',                                        'alias_opd' => 'NAG. PADANG MENTINGGI UT', 'order' => 98],
            ['nama_opd' => 'NAGARI TARUANG TARUANG',                                                'alias_opd' => 'NAG. TARUANG TARUANG', 'order' => 99],
            ['nama_opd' => 'NAGARI TARUANG UTARA',                                                  'alias_opd' => 'NAG. TARUANG UTARA',   'order' => 100],
            ['nama_opd' => 'NAGARI TARUANG SELATAN',                                                'alias_opd' => 'NAG. TARUANG SEL',     'order' => 101],
            ['nama_opd' => 'NAGARI LUBUK LAYANG',                                                   'alias_opd' => 'NAG. LUBUK LAYANG',    'order' => 102],
            ['nama_opd' => 'NAGARI LANSECK KADOK',                                                  'alias_opd' => 'NAG. LANSECK KADOK',   'order' => 103],
            ['nama_opd' => 'NAGARI LANSECK KADOK BARAT',                                            'alias_opd' => 'NAG. LANSECK KADOK BAR', 'order' => 104],
            ['nama_opd' => 'NAGARI TANJUNG BETUNG',                                                 'alias_opd' => 'NAG. TANJUNG BETUNG',  'order' => 105],
            ['nama_opd' => 'NAGARI TANJUNG BETUNG UTARA',                                           'alias_opd' => 'NAG. TANJUNG BETUNG UT', 'order' => 106],
            ['nama_opd' => 'NAGARI TANJUNG BETUNG TIMUR',                                           'alias_opd' => 'NAG. TANJUNG BETUNG TIM', 'order' => 107],
            ['nama_opd' => 'NAGARI LANGUANG',                                                       'alias_opd' => 'NAG. LANGUANG',        'order' => 108],
            ['nama_opd' => 'NAGARI KOTO RAJO',                                                      'alias_opd' => 'NAG. KOTO RAJO',       'order' => 109],
            ['nama_opd' => 'NAGARI KOTO NOPAN',                                                     'alias_opd' => 'NAG. KOTO NOPAN',      'order' => 110],
            ['nama_opd' => 'NAGARI MUARO TAIS',                                                     'alias_opd' => 'NAG. MUARO TAIS',      'order' => 111],
            ['nama_opd' => 'NAGARI MUARO TAIS KOTO GADANG',                                         'alias_opd' => 'NAG. MUARO TAIS KOTO GADANG', 'order' => 112],
            ['nama_opd' => 'NAGARI LUBUK GADANG',                                                   'alias_opd' => 'NAG. LUBUK GADANG',    'order' => 113],
            ['nama_opd' => 'NAGARI PINTU PADANG',                                                   'alias_opd' => 'NAG. PINTU PADANG',    'order' => 114],
            ['nama_opd' => 'NAGARI SILAYANG',                                                       'alias_opd' => 'NAG. SILAYANG',        'order' => 115],
            ['nama_opd' => 'NAGARI MUARO SUNGAI LOLO',                                             'alias_opd' => 'NAG. MUARO SUNGAI LOLO', 'order' => 116],
            ['nama_opd' => 'PERUMDA TIRTA SAIYO (PDAM)',                                           'alias_opd' => 'PDAM',                 'order' => 117],
        ];

        $kodePool = range(101, 299);
        shuffle($kodePool);

        $insert = [];
        foreach ($data as $i => $item) {
            $insert[] = [
                'id'         => Str::uuid(),
                'kode_opd'   => (string) $kodePool[$i],
                'nama_opd'   => $item['nama_opd'],
                'alias_opd'  => $item['alias_opd'],
                'order'      => $item['order'],
                'is_active'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        \DB::table('master_opd')->insert($insert);
    }
}
