const GET_LIST_POHONKINERJA_KDH_START = "GET_LIST_POHONKINERJA_KDH_START"
const GET_LIST_POHONKINERJA_KDH_SUCCESS = "GET_LIST_POHONKINERJA_KDH_SUCCESS"
const GET_LIST_POHONKINERJA_KDH_FAILED = "GET_LIST_POHONKINERJA_KDH_FAILED"

export {
    GET_LIST_POHONKINERJA_KDH_START,
    GET_LIST_POHONKINERJA_KDH_SUCCESS,
    GET_LIST_POHONKINERJA_KDH_FAILED
}