const GET_LIST_RENAKSIOPD_START = "GET_LIST_RENAKSIOPD_START"
const GET_LIST_RENAKSIOPD_SUCCESS = "GET_LIST_RENAKSIOPD_SUCCESS"
const GET_LIST_RENAKSIOPD_FAILED = "GET_LIST_RENAKSIOPD_FAILED"

const CREATE_RENAKSIOPD_START = "CREATE_RENAKSIOPD_START"
const CREATE_RENAKSIOPD_SUCCESS = "CREATE_RENAKSIOPD_SUCCESS"
const CREATE_RENAKSIOPD_FAILED = "CREATE_RENAKSIOPD_FAILED"

const GET_LIST_RENAKSIOPD_LANGKAH_START = "GET_LIST_RENAKSIOPD_LANGKAH_START"
const GET_LIST_RENAKSIOPD_LANGKAH_SUCCESS = "GET_LIST_RENAKSIOPD_LANGKAH_SUCCESS"
const GET_LIST_RENAKSIOPD_LANGKAH_FAILED = "GET_LIST_RENAKSIOPD_LANGKAH_FAILED"

const CREATE_RENAKSIOPD_LANGKAH_START = "CREATE_RENAKSIOPD_LANGKAH_START"
const CREATE_RENAKSIOPD_LANGKAH_SUCCESS = "CREATE_RENAKSIOPD_LANGKAH_SUCCESS"
const CREATE_RENAKSIOPD_LANGKAH_FAILED = "CREATE_RENAKSIOPD_LANGKAH_FAILED"

const UPDATE_RENAKSIOPD_LANGKAH_START = "UPDATE_RENAKSIOPD_LANGKAH_START"
const UPDATE_RENAKSIOPD_LANGKAH_SUCCESS = "UPDATE_RENAKSIOPD_LANGKAH_SUCCESS"
const UPDATE_RENAKSIOPD_LANGKAH_FAILED = "UPDATE_RENAKSIOPD_LANGKAH_FAILED"

const DELETE_RENAKSIOPD_LANGKAH_START = "DELETE_RENAKSIOPD_LANGKAH_START"
const DELETE_RENAKSIOPD_LANGKAH_SUCCESS = "DELETE_RENAKSIOPD_LANGKAH_SUCCESS"
const DELETE_RENAKSIOPD_LANGKAH_FAILED = "DELETE_RENAKSIOPD_LANGKAH_FAILED"

export {
    GET_LIST_RENAKSIOPD_START,
    GET_LIST_RENAKSIOPD_SUCCESS,
    GET_LIST_RENAKSIOPD_FAILED,

    CREATE_RENAKSIOPD_START,
    CREATE_RENAKSIOPD_SUCCESS,
    CREATE_RENAKSIOPD_FAILED,

    GET_LIST_RENAKSIOPD_LANGKAH_START,
    GET_LIST_RENAKSIOPD_LANGKAH_SUCCESS,
    GET_LIST_RENAKSIOPD_LANGKAH_FAILED,

    CREATE_RENAKSIOPD_LANGKAH_START,
    CREATE_RENAKSIOPD_LANGKAH_SUCCESS,
    CREATE_RENAKSIOPD_LANGKAH_FAILED,

    UPDATE_RENAKSIOPD_LANGKAH_START,
    UPDATE_RENAKSIOPD_LANGKAH_SUCCESS,
    UPDATE_RENAKSIOPD_LANGKAH_FAILED,

    DELETE_RENAKSIOPD_LANGKAH_START,
    DELETE_RENAKSIOPD_LANGKAH_SUCCESS,
    DELETE_RENAKSIOPD_LANGKAH_FAILED
}