const GET_LIST_POHONKINERJA_OPD_START = "GET_LIST_POHONKINERJA_OPD_START"
const GET_LIST_POHONKINERJA_OPD_SUCCESS = "GET_LIST_POHONKINERJA_OPD_SUCCESS"
const GET_LIST_POHONKINERJA_OPD_FAILED = "GET_LIST_POHONKINERJA_OPD_FAILED"

export {
    GET_LIST_POHONKINERJA_OPD_START,
    GET_LIST_POHONKINERJA_OPD_SUCCESS,
    GET_LIST_POHONKINERJA_OPD_FAILED
}