const GET_LIST_INDIKATOROPERASIONALOPD_START = "GET_LIST_INDIKATOROPERASIONALOPD_START"
const GET_LIST_INDIKATOROPERASIONALOPD_SUCCESS = "GET_LIST_INDIKATOROPERASIONALOPD_SUCCESS"
const GET_LIST_INDIKATOROPERASIONALOPD_FAILED = "GET_LIST_INDIKATOROPERASIONALOPD_FAILED"

const GET_REF_INDIKATOROPERASIONALOPD_START = "GET_REF_INDIKATOROPERASIONALOPD_START"
const GET_REF_INDIKATOROPERASIONALOPD_SUCCESS = "GET_REF_INDIKATOROPERASIONALOPD_SUCCESS"
const GET_REF_INDIKATOROPERASIONALOPD_FAILED = "GET_REF_INDIKATOROPERASIONALOPD_FAILED"

const CREATE_INDIKATOROPERASIONALOPD_START = "CREATE_INDIKATOROPERASIONALOPD_START"
const CREATE_INDIKATOROPERASIONALOPD_SUCCESS = "CREATE_INDIKATOROPERASIONALOPD_SUCCESS"
const CREATE_INDIKATOROPERASIONALOPD_FAILED = "CREATE_INDIKATOROPERASIONALOPD_FAILED"

const GET_INDIKATOROPERASIONALOPD_START = "GET_INDIKATOROPERASIONALOPD_START"
const GET_INDIKATOROPERASIONALOPD_SUCCESS = "GET_INDIKATOROPERASIONALOPD_SUCCESS"
const GET_INDIKATOROPERASIONALOPD_FAILED = "GET_INDIKATOROPERASIONALOPD_FAILED"

const DELETE_INDIKATOROPERASIONALOPD_START = "DELETE_INDIKATOROPERASIONALOPD_START"
const DELETE_INDIKATOROPERASIONALOPD_SUCCESS = "DELETE_INDIKATOROPERASIONALOPD_SUCCESS"
const DELETE_INDIKATOROPERASIONALOPD_FAILED = "DELETE_INDIKATOROPERASIONALOPD_FAILED"

export {
    GET_LIST_INDIKATOROPERASIONALOPD_START,
    GET_LIST_INDIKATOROPERASIONALOPD_SUCCESS,
    GET_LIST_INDIKATOROPERASIONALOPD_FAILED,

    GET_REF_INDIKATOROPERASIONALOPD_START,
    GET_REF_INDIKATOROPERASIONALOPD_SUCCESS,
    GET_REF_INDIKATOROPERASIONALOPD_FAILED,

    CREATE_INDIKATOROPERASIONALOPD_START,
    CREATE_INDIKATOROPERASIONALOPD_SUCCESS,
    CREATE_INDIKATOROPERASIONALOPD_FAILED,

    GET_INDIKATOROPERASIONALOPD_START,
    GET_INDIKATOROPERASIONALOPD_SUCCESS,
    GET_INDIKATOROPERASIONALOPD_FAILED,

    DELETE_INDIKATOROPERASIONALOPD_START,
    DELETE_INDIKATOROPERASIONALOPD_SUCCESS,
    DELETE_INDIKATOROPERASIONALOPD_FAILED
}