const GET_LIST_INDIKATOROPD_START        = "GET_LIST_INDIKATOROPD_START"
const GET_LIST_INDIKATOROPD_SUCCESS      = "GET_LIST_INDIKATOROPD_SUCCESS"
const GET_LIST_INDIKATOROPD_FAILED       = "GET_LIST_INDIKATOROPD_FAILED"

const CREATE_INDIKATOROPD_START          = "CREATE_INDIKATOROPD_START"
const CREATE_INDIKATOROPD_SUCCESS        = "CREATE_INDIKATOROPD_SUCCESS"
const CREATE_INDIKATOROPD_FAILED         = "CREATE_INDIKATOROPD_FAILED"

const GET_INDIKATOROPD_START             = "GET_INDIKATOROPD_START"
const GET_INDIKATOROPD_SUCCESS           = "GET_INDIKATOROPD_SUCCESS"
const GET_INDIKATOROPD_FAILED            = "GET_INDIKATOROPD_FAILED"

const UPDATE_INDIKATOROPD_START          = "UPDATE_INDIKATOROPD_START"
const UPDATE_INDIKATOROPD_SUCCESS        = "UPDATE_INDIKATOROPD_SUCCESS"
const UPDATE_INDIKATOROPD_FAILED         = "UPDATE_INDIKATOROPD_FAILED"

const DELETE_INDIKATOROPD_START          = "DELETE_INDIKATOROPD_START"
const DELETE_INDIKATOROPD_SUCCESS        = "DELETE_INDIKATOROPD_SUCCESS"
const DELETE_INDIKATOROPD_FAILED         = "DELETE_INDIKATOROPD_FAILED"

export {
    GET_LIST_INDIKATOROPD_START, GET_LIST_INDIKATOROPD_SUCCESS, GET_LIST_INDIKATOROPD_FAILED,
    CREATE_INDIKATOROPD_START, CREATE_INDIKATOROPD_SUCCESS, CREATE_INDIKATOROPD_FAILED,
    GET_INDIKATOROPD_START, GET_INDIKATOROPD_SUCCESS, GET_INDIKATOROPD_FAILED,
    UPDATE_INDIKATOROPD_START, UPDATE_INDIKATOROPD_SUCCESS, UPDATE_INDIKATOROPD_FAILED,
    DELETE_INDIKATOROPD_START, DELETE_INDIKATOROPD_SUCCESS, DELETE_INDIKATOROPD_FAILED
}