const GET_LIST_DATAMASTEROPD_START       = "GET_LIST_DATAMASTEROPD_START"
const GET_LIST_DATAMASTEROPD_SUCCESS     = "GET_LIST_DATAMASTEROPD_SUCCESS"
const GET_LIST_DATAMASTEROPD_FAILED      = "GET_LIST_DATAMASTEROPD_FAILED"

const CREATE_DATAMASTEROPD_START         = "CREATE_DATAMASTEROPD_START"
const CREATE_DATAMASTEROPD_SUCCESS       = "CREATE_DATAMASTEROPD_SUCCESS"
const CREATE_DATAMASTEROPD_FAILED        = "CREATE_DATAMASTEROPD_FAILED"

const GET_DATAMASTEROPD_START            = "GET_DATAMASTEROPD_START"
const GET_DATAMASTEROPD_SUCCESS          = "GET_DATAMASTEROPD_SUCCESS"
const GET_DATAMASTEROPD_FAILED           = "GET_DATAMASTEROPD_FAILED"

const UPDATE_DATAMASTEROPD_START         = "UPDATE_DATAMASTEROPD_START"
const UPDATE_DATAMASTEROPD_SUCCESS       = "UPDATE_DATAMASTEROPD_SUCCESS"
const UPDATE_DATAMASTEROPD_FAILED        = "UPDATE_DATAMASTEROPD_FAILED"

const DELETE_DATAMASTEROPD_START         = "DELETE_DATAMASTEROPD_START"
const DELETE_DATAMASTEROPD_SUCCESS       = "DELETE_DATAMASTEROPD_SUCCESS"
const DELETE_DATAMASTEROPD_FAILED        = "DELETE_DATAMASTEROPD_FAILED"

const GET_OPTIONSOPD_START               = "GET_OPTIONSOPD_START"
const GET_OPTIONSOPD_SUCCESS             = "GET_OPTIONSOPD_SUCCESS"
const GET_OPTIONSOPD_FAILED              = "GET_OPTIONSOPD_FAILED"

export {
    GET_LIST_DATAMASTEROPD_START,
    GET_LIST_DATAMASTEROPD_SUCCESS,
    GET_LIST_DATAMASTEROPD_FAILED,

    CREATE_DATAMASTEROPD_START,
    CREATE_DATAMASTEROPD_SUCCESS,
    CREATE_DATAMASTEROPD_FAILED,

    GET_DATAMASTEROPD_START,
    GET_DATAMASTEROPD_SUCCESS,
    GET_DATAMASTEROPD_FAILED,

    UPDATE_DATAMASTEROPD_START,
    UPDATE_DATAMASTEROPD_SUCCESS,
    UPDATE_DATAMASTEROPD_FAILED,

    DELETE_DATAMASTEROPD_START,
    DELETE_DATAMASTEROPD_SUCCESS,
    DELETE_DATAMASTEROPD_FAILED,

    GET_OPTIONSOPD_START,
    GET_OPTIONSOPD_SUCCESS,
    GET_OPTIONSOPD_FAILED
}