import {
    Authorization,
    Dashboard,
    Satuan, Opd, Pegawai,
    Kdh,
    PohonKinerja, PohonKinerjaView,
    Visi, Misi, Tujuan, Sasaran, Indikator,
    CascadingKdh, AddCascadingKdh,
    TargetRpjmd, IndikatorKinerjaUtama, IkuEdit,
    RkpdDashboard, RkpdForm, RkpdProgramAnggaran,
    PkDashboard, PkForm, PkProgramAnggaran,
    RaPage, LangkahRa,

    PerangkatDaerah, TujuanOpd, SasaranOpd, IndikatorOpd, PohonKinerjaOpdView,
    CascadingOpd, AddCascadingOpd,
    TargetRenstra,
    IkuOpd, IkuOpdEdit,
    RenjaDashboard, RenjaForm, RenjaProgramAnggaran,
    PkOpdDashboard, PkOpdForm, PkOpdProgramAnggaran,
    RaOpdPage, LangkahRaOpd,

    SasaranOperasionalOpd,
    IndikatorOperasionalOpd,

    RealisasiRenaksiKdh,
    LangkahRealisasiRenaksiKdh,
    
    RealisasiRenaksiOpd,
    LangkahRealisasiRenaksiOpd,

    PkPegawaiDashboard,
    PkPegawaiForm,
    PkPegawaiProgramAnggaran,

    RaPegawaiPage, LangkahRaPegawai,

    RealisasiRenaksiPegawai, LangkahRealisasiRenaksiPegawai,

    DataKinerjaKdh, CapaianKinerjaKdh, AnalisisKinerjaKdh, EfisiensiAnggaranKdh,

    DataKinerjaOpd, CapaianKinerjaOpd, AnalisisKinerjaOpd, EfisiensiAnggaranOpd,

    SkpList, SkpTarget, SkpDetail, SkpRenaksi, SkpDetailRealisasi, SkpRenaksiRealisasi,

    Profile,

    DashboardOpd, PohonKinerjaOpd, MonitorPohonKinerjaOpdView, MonitorCascadingOpd,
    MonitorRenstraOpd, MonitorIkuOpd, MonitorRenjaOpd, MonitorPkOpd, MonitorRencanaAksiOpd,
    MonitorRealisasiRenaksiOpd, MonitorDataKinerjaOpd, MonitorCapaianKinerjaOpd
} from "@pages"

const routes = [
    {
        key: 'authorization-sso-sumbar',
        name: 'authorization-sso-sumbar',
        Component: Authorization,
        path: '/authorization',
    },
    {
        key: 'dashboard-sakip',
        name: 'dashboard-sakip',
        Component: Dashboard,
        path: '/dashboard',
    },
    {
        key: 'data-master-satuan',
        name: 'data-master-satuan',
        Component: Satuan,
        path: '/datamaster/satuan',
    },
    {
        key: 'data-master-opd',
        name: 'data-master-opd',
        Component: Opd,
        path: '/datamaster/opd',
    },
    {
        key: 'data-master-pegawai',
        name: 'data-master-pegawai',
        Component: Pegawai,
        path: '/datamaster/pegawai',
    },
    {
        key: 'perencanaan-kepala-daerah',
        name: 'perencanaan-kepala-daerah',
        Component: Kdh,
        path: '/perencanaan/kdh',
    },
    {
        key: 'perencanaan-kepala-daerah-pohonkinerja',
        name: 'perencanaan-kepala-daerah-pohonkinerja',
        Component: PohonKinerja,
        path: '/perencanaan/kdh/pohonkinerja',
    },
    {
        key: 'perencanaan-kepala-daerah-pohonkinerja-view',
        name: 'perencanaan-kepala-daerah-pohonkinerja-view',
        Component: PohonKinerjaView,
        path: '/perencanaan/kdh/pohonkinerja/view',
    },
    {
        key: 'perencanaan-kepala-daerah-pohonkinerja-visi',
        name: 'perencanaan-kepala-daerah-pohonkinerja-visi',
        Component: Visi,
        path: '/perencanaan/kdh/pohonkinerja/visi',
    },
    {
        key: 'perencanaan-kepala-daerah-pohonkinerja-misi',
        name: 'perencanaan-kepala-daerah-pohonkinerja-misi',
        Component: Misi,
        path: '/perencanaan/kdh/pohonkinerja/misi',
    },
    {
        key: 'perencanaan-kepala-daerah-pohonkinerja-tujuan',
        name: 'perencanaan-kepala-daerah-pohonkinerja-tujuan',
        Component: Tujuan,
        path: '/perencanaan/kdh/pohonkinerja/tujuan',
    },
    {
        key: 'perencanaan-kepala-daerah-pohonkinerja-sasaran',
        name: 'perencanaan-kepala-daerah-pohonkinerja-sasaran',
        Component: Sasaran,
        path: '/perencanaan/kdh/pohonkinerja/sasaran',
    },
    {
        key: 'perencanaan-kepala-daerah-pohonkinerja-indikator',
        name: 'perencanaan-kepala-daerah-pohonkinerja-indikator',
        Component: Indikator,
        path: '/perencanaan/kdh/pohonkinerja/indikator',
    },
    {
        key: 'perencanaan-kepala-daerah-cascading',
        name: 'perencanaan-kepala-daerah-cascading',
        Component: CascadingKdh,
        path: '/perencanaan/kdh/cascading',
    },
    {
        key: 'perencanaan-kepala-daerah-cascading-add',
        name: 'perencanaan-kepala-daerah-cascading-add',
        Component: AddCascadingKdh,
        path: '/perencanaan/kdh/cascading/add',
    },
    {
        key: 'perencanaan-kepala-daerah-rpjmd',
        name: 'perencanaan-kepala-daerah-rpjmd',
        Component: TargetRpjmd,
        path: '/perencanaan/kdh/rpjmd',
    },
    {
        key: 'perencanaan-kepala-daerah-iku',
        name: 'perencanaan-kepala-daerah-iku',
        Component: IndikatorKinerjaUtama,
        path: '/perencanaan/kdh/iku',
    },
    {
        key: 'perencanaan-kepala-daerah-iku-edit',
        name: 'perencanaan-kepala-daerah-iku-edit',
        Component: IkuEdit,
        path: '/perencanaan/kdh/iku/:id',
    },
    {
        key: 'perencanaan-kepala-daerah-rkpd-dashboard',
        name: 'perencanaan-kepala-daerah-rkpd-dashboard',
        Component: RkpdDashboard,
        path: '/perencanaan/kdh/rkpd',
    },
    {
        key: 'perencanaan-kepala-daerah-rkpd-form',
        name: 'perencanaan-kepala-daerah-rkpd-form',
        Component: RkpdForm,
        path: '/perencanaan/kdh/rkpd/:period/:type',
    },
    {
        key: 'perencanaan-kepala-daerah-rkpd-program-anggaran',
        name: 'perencanaan-kepala-daerah-rkpd-program-anggaran',
        Component: RkpdProgramAnggaran,
        path: '/perencanaan/kdh/rkpd/:period/:type/program',
    },
    {
        key: 'perencanaan-kepala-daerah-pk-dashboard',
        name: 'perencanaan-kepala-daerah-pk-dashboard',
        Component: PkDashboard,
        path: '/perencanaan/kdh/pk',
    },
    {
        key: 'perencanaan-kepala-daerah-pk-form',
        name: 'perencanaan-kepala-daerah-pk-form',
        Component: PkForm,
        path: '/perencanaan/kdh/pk/:period/:type',
    },
    {
        key: 'perencanaan-kepala-daerah-pk-program-anggaran',
        name: 'perencanaan-kepala-daerah-pk-program-anggaran',
        Component: PkProgramAnggaran,
        path: '/perencanaan/kdh/pk/:period/:type/program',
    },
    {
        key: 'perencanaan-kepala-daerah-ra',
        name: 'perencanaan-kepala-daerah-ra',
        Component: RaPage,
        path: '/perencanaan/kdh/ra',
    },
    {
        key: 'perencanaan-kepala-daerah-ra-langkah',
        name: 'perencanaan-kepala-daerah-ra-langkah',
        Component: LangkahRa,
        path: '/perencanaan/kdh/ra/langkah',
    },
    {
        key: 'perencanaan-perangkat-daerah',
        name: 'perencanaan-perangkat-daerah',
        Component: PerangkatDaerah,
        path: '/perencanaan/opd',
    },
    {
        key: 'perencanaan-perangkat-daerah-pohonkinerja-tujuan',
        name: 'perencanaan-perangkat-daerah-pohonkinerja-tujuan',
        Component: TujuanOpd,
        path: '/perencanaan/opd/pohonkinerja/tujuan',
    },
    {
        key: 'perencanaan-perangkat-daerah-pohonkinerja-sasaran',
        name: 'perencanaan-perangkat-daerah-pohonkinerja-sasaran',
        Component: SasaranOpd,
        path: '/perencanaan/opd/pohonkinerja/sasaran',
    },
    {
        key: 'perencanaan-perangkat-daerah-pohonkinerja-indikator',
        name: 'perencanaan-perangkat-daerah-pohonkinerja-indikator',
        Component: IndikatorOpd,
        path: '/perencanaan/opd/pohonkinerja/indikator',
    },
    {
        key: 'perencanaan-perangkat-daerah-cascading',
        name: 'perencanaan-perangkat-daerah-cascading',
        Component: CascadingOpd,
        path: '/perencanaan/opd/cascading',
    },
    {
        key: 'perencanaan-perangkat-daerah-cascading-add',
        name: 'perencanaan-perangkat-daerah-cascading-add',
        Component: AddCascadingOpd,
        path: '/perencanaan/opd/cascading/add',
    },
    {
        key: 'perencanaan-perangkat-daerah-renstra',
        name: 'perencanaan-perangkat-daerah-renstra',
        Component: TargetRenstra,
        path: '/perencanaan/opd/renstra',
    },
    {
        key: 'perencanaan-perangkat-daerah-iku',
        name: 'perencanaan-perangkat-daerah-iku',
        Component: IkuOpd,
        path: '/perencanaan/opd/iku',
    },
    {
        key: 'perencanaan-perangkat-daerah-iku-edit',
        name: 'perencanaan-perangkat-daerah-iku-edit',
        Component: IkuOpdEdit,
        path: '/perencanaan/opd/iku/:id',
    },
    {
        key: 'perencanaan-perangkat-daerah-renja-dashboard',
        name: 'perencanaan-perangkat-daerah-renja-dashboard',
        Component: RenjaDashboard,
        path: '/perencanaan/opd/renja',
    },
    {
        key: 'perencanaan-perangkat-daerah-renja-form',
        name: 'perencanaan-perangkat-daerah-renja-form',
        Component: RenjaForm,
        path: '/perencanaan/opd/renja/:period/:type',
    },
    {
        key: 'perencanaan-perangkat-daerah-renja-program-anggaran',
        name: 'perencanaan-perangkat-daerah-renja-program-anggaran',
        Component: RenjaProgramAnggaran,
        path: '/perencanaan/opd/renja/:period/:type/program',
    },
    {
        key: 'perencanaan-perangkat-daerah-pkopd-dashboard',
        name: 'perencanaan-perangkat-daerah-pkopd-dashboard',
        Component: PkOpdDashboard,
        path: '/perencanaan/opd/pk',
    },
    {
        key: 'perencanaan-perangkat-daerah-pkopd-form',
        name: 'perencanaan-perangkat-daerah-pkopd-form',
        Component: PkOpdForm,
        path: '/perencanaan/opd/pk/:period/:type',
    },
    {
        key: 'perencanaan-perangkat-daerah-pkopd-program-anggaran',
        name: 'perencanaan-perangkat-daerah-pkopd-program-anggaran',
        Component: PkOpdProgramAnggaran,
        path: '/perencanaan/opd/pk/:period/:type/program',
    },
    {
        key: 'perencanaan-perangkat-daerah-ra',
        name: 'perencanaan-perangkat-daerah-ra',
        Component: RaOpdPage,
        path: '/perencanaan/opd/ra',
    },
    {
        key: 'perencanaan-perangkat-daerah-ra-langkah',
        name: 'perencanaan-perangkat-daerah-ra-langkah',
        Component: LangkahRaOpd,
        path: '/perencanaan/opd/ra/langkah',
    },
    {
        key: 'perencanaan-perangkat-daerah-pohon-kinerja-view',
        name: 'perencanaan-perangkat-daerah-pohon-kinerja-view',
        Component: PohonKinerjaOpdView,
        path: '/perencanaan/opd/pohonkinerja/view',
    },
    {
        key: 'pengukuran-kepala-daerah-realisasi-renaksi',
        name: 'pengukuran-kepala-daerah-realisasi-renaksi',
        Component: RealisasiRenaksiKdh,
        path: '/pengukuran/kdh/realisasirenaksi',
    },
    {
        key: 'pengukuran-kepala-daerah-langkah-realisasi-renaksi',
        name: 'pengukuran-kepala-daerah-langkah-realisasi-renaksi',
        Component: LangkahRealisasiRenaksiKdh,
        path: '/pengukuran/kdh/realisasirenaksi/langkah',
    },
    {
        key: 'pengukuran-perangkat-daerah-realisasi-renaksi',
        name: 'pengukuran-perangkat-daerah-realisasi-renaksi',
        Component: RealisasiRenaksiOpd,
        path: '/pengukuran/opd/realisasirenaksi',
    },
    {
        key: 'pengukuran-perangkat-daerah-langkah-realisasi-renaksi',
        name: 'pengukuran-perangkat-daerah-langkah-realisasi-renaksi',
        Component: LangkahRealisasiRenaksiOpd,
        path: '/pengukuran/opd/realisasirenaksi/langkah',
    },
    {
        key: 'perencanaan-perangkat-daerah-sasaran-operasional',
        name: 'perencanaan-perangkat-daerah-sasaran-operasional',
        Component: SasaranOperasionalOpd,
        path: '/perencanaan/opd/sasaran_operasional',
    },
    {
        key: 'perencanaan-perangkat-daerah-indikator-operasional',
        name: 'perencanaan-perangkat-daerah-indikator-operasional',
        Component: IndikatorOperasionalOpd,
        path: '/perencanaan/opd/indikator_operasional',
    },
    {
        key: 'perencanaan-pegawai-pk-dashboard',
        name: 'perencanaan-pegawai-pk-dashboard',
        Component: PkPegawaiDashboard,
        path: '/pegawai/pk',
    },
    {
        key: 'perencanaan-pegawai-pk-form',
        name: 'perencanaan-pegawai-pk-form',
        Component: PkPegawaiForm,
        path: '/pegawai/pk/:period/:type',
    },
    {
        key: 'perencanaan-pegawai-pk-form',
        name: 'perencanaan-pegawai-pk-form',
        Component: PkPegawaiProgramAnggaran,
        path: '/pegawai/pk/:period/:type/program',
    },
    {
        key: 'perencanaan-pegawai-ra',
        name: 'perencanaan-pegawai-ra',
        Component: RaPegawaiPage,
        path: '/pegawai/ra',
    },
    {
        key: 'perencanaan-pegawai-ra-langkah',
        name: 'perencanaan-pegawai-ra-langkah',
        Component: LangkahRaPegawai,
        path: '/pegawai/ra/langkah',
    },
    {
        key: 'perencanaan-pegawai-realisasi-renaksi',
        name: 'perencanaan-pegawai-realisasi-renaksi',
        Component: RealisasiRenaksiPegawai,
        path: '/pegawai/realisasirenaksi',
    },
    {
        key: 'perencanaan-pegawai-realisasi-renaksi-langkah',
        name: 'perencanaan-pegawai-realisasi-renaksi-langkah',
        Component: LangkahRealisasiRenaksiPegawai,
        path: '/pegawai/realisasirenaksi/langkah',
    },
    {
        key: 'pelaporan-data-kinerja-kepala-daerah',
        name: 'pelaporan-data-kinerja-kepala-daerah',
        Component: DataKinerjaKdh,
        path: '/pelaporan/kdh/kinerja',
    },
    {
        key: 'pelaporan-capaian-kinerja-kepala-daerah',
        name: 'pelaporan-capaian-kinerja-kepala-daerah',
        Component: CapaianKinerjaKdh,
        path: '/pelaporan/kdh/capaiankinerja',
    },
    {
        key: 'pelaporan-analisis-kinerja-kepala-daerah',
        name: 'pelaporan-analisis-kinerja-kepala-daerah',
        Component: AnalisisKinerjaKdh,
        path: '/pelaporan/kdh/analisiskinerja',
    },
    {
        key: 'pelaporan-efisiensi-anggaran-kepala-daerah',
        name: 'pelaporan-efisiensi-anggaran-kepala-daerah',
        Component: EfisiensiAnggaranKdh,
        path: '/pelaporan/kdh/efisiensianggaran',
    },
    {
        key: 'pelaporan-data-kinerja-perangkat-daerah',
        name: 'pelaporan-data-kinerja-perangkat-daerah',
        Component: DataKinerjaOpd,
        path: '/pelaporan/opd/kinerja',
    },
    {
        key: 'pelaporan-capaian-kinerja-perangkat-daerah',
        name: 'pelaporan-capaian-kinerja-perangkat-daerah',
        Component: CapaianKinerjaOpd,
        path: '/pelaporan/opd/capaiankinerja',
    },
    {
        key: 'pelaporan-analisis-kinerja-perangkat-daerah',
        name: 'pelaporan-analisis-kinerja-perangkat-daerah',
        Component: AnalisisKinerjaOpd,
        path: '/pelaporan/opd/analisiskinerja',
    },
    {
        key: 'pelaporan-efisiensi-anggaran-perangkat-daerah',
        name: 'pelaporan-efisiensi-anggaran-perangkat-daerah',
        Component: EfisiensiAnggaranOpd,
        path: '/pelaporan/opd/efisiensianggaran',
    },
    {
        key: 'perencanaan-pegawai-skp',
        name: 'perencanaan-pegawai-skp',
        Component: SkpList,
        path: '/pegawai/skp',
    },
    {
        key: 'perencanaan-pegawai-skp-detail',
        name: 'perencanaan-pegawai-skp-detail',
        Component: SkpTarget,
        path: '/pegawai/skp/:id',
    },
    {
        key: 'perencanaan-pegawai-skp-detail',
        name: 'perencanaan-pegawai-skp-detail',
        Component: SkpDetail,
        path: '/pegawai/skp/details/:id',
    },
    {
        key: 'perencanaan-pegawai-skp-renaksi',
        name: 'perencanaan-pegawai-skp-renaksi',
        Component: SkpRenaksi,
        path: '/pegawai/skp/:idskp/rencana-aksi/:id',
    },
    {
        key: 'pengukuran-pegawai-skp',
        name: 'pengukuran-pegawai-skp',
        Component: SkpDetailRealisasi,
        path: '/pegawai/realisasiskp',
    },
    {
        key: 'pengukuran-pegawai-skp-renaksi',
        name: 'pengukuran-pegawai-skp-renaksi',
        Component: SkpRenaksiRealisasi,
        path: '/pegawai/realisasiskp/:idskp/rencana-aksi/:id',
    },
    {
        key: 'profile',
        name: 'profile',
        Component: Profile,
        path: '/profile',
    },
    {
        key: 'monitoring-perangkat-daerah',
        name: 'monitoring-perangkat-daerah',
        Component: DashboardOpd,
        path: '/monitoring/opd',
    },
    {
        key: 'monitoring-perangkat-daerah-pohonkinerja',
        name: 'monitoring-perangkat-daerah-pohonkinerja',
        Component: PohonKinerjaOpd,
        path: '/monitoring/opd/pohonkinerja/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-pohonkinerja-view',
        name: 'monitoring-perangkat-daerah-pohonkinerja-view',
        Component: MonitorPohonKinerjaOpdView,
        path: '/monitoring/opd/pohonkinerja/view/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-cascading',
        name: 'monitoring-perangkat-daerah-cascading',
        Component: MonitorCascadingOpd,
        path: '/monitoring/opd/cascading/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-renstra',
        name: 'monitoring-perangkat-daerah-renstra',
        Component: MonitorRenstraOpd,
        path: '/monitoring/opd/renstra/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-iku',
        name: 'monitoring-perangkat-daerah-iku',
        Component: MonitorIkuOpd,
        path: '/monitoring/opd/iku/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-renja',
        name: 'monitoring-perangkat-daerah-renja',
        Component: MonitorRenjaOpd,
        path: '/monitoring/opd/renja/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-pk',
        name: 'monitoring-perangkat-daerah-pk',
        Component: MonitorPkOpd,
        path: '/monitoring/opd/pk/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-rencana-aksi',
        name: 'monitoring-perangkat-daerah-rencana-aksi',
        Component: MonitorRencanaAksiOpd,
        path: '/monitoring/opd/ra/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-realisasi-renaksi',
        name: 'monitoring-perangkat-daerah-realisasi-renaksi',
        Component: MonitorRealisasiRenaksiOpd,
        path: '/monitoring/opd/realisasirenaksi/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-datakinerja',
        name: 'monitoring-perangkat-daerah-datakinerja',
        Component: MonitorDataKinerjaOpd,
        path: '/monitoring/opd/datakinerja/:idopd',
    },
    {
        key: 'monitoring-perangkat-daerah-capaiankinerja',
        name: 'monitoring-perangkat-daerah-capaiankinerja',
        Component: MonitorCapaianKinerjaOpd,
        path: '/monitoring/opd/capaiankinerja/:idopd',
    },
]

export default routes