const SET_SELECTED_OPD = "SET_SELECTED_OPD"
const CLEAR_SELECTED_OPD = "CLEAR_SELECTED_OPD"

const GET_LIST_MONITORING_POHONKINERJA_OPD_START = "GET_LIST_MONITORING_POHONKINERJA_OPD_START"
const GET_LIST_MONITORING_POHONKINERJA_OPD_SUCCESS = "GET_LIST_MONITORING_POHONKINERJA_OPD_SUCCESS"
const GET_LIST_MONITORING_POHONKINERJA_OPD_FAILED = "GET_LIST_MONITORING_POHONKINERJA_OPD_FAILED"

const GET_LIST_MONITORING_CASCADING_OPD_START = "GET_LIST_MONITORING_CASCADING_OPD_START"
const GET_LIST_MONITORING_CASCADING_OPD_SUCCESS = "GET_LIST_MONITORING_CASCADING_OPD_SUCCESS"
const GET_LIST_MONITORING_CASCADING_OPD_FAILED = "GET_LIST_MONITORING_CASCADING_OPD_FAILED"

const GET_LIST_MONITORING_RENSTRA_OPD_START = "GET_LIST_MONITORING_RENSTRA_OPD_START"
const GET_LIST_MONITORING_RENSTRA_OPD_SUCCESS = "GET_LIST_MONITORING_RENSTRA_OPD_SUCCESS"
const GET_LIST_MONITORING_RENSTRA_OPD_FAILED = "GET_LIST_MONITORING_RENSTRA_OPD_FAILED"

const GET_LIST_MONITORING_IKU_OPD_START = "GET_LIST_MONITORING_IKU_OPD_START"
const GET_LIST_MONITORING_IKU_OPD_SUCCESS = "GET_LIST_MONITORING_IKU_OPD_SUCCESS"
const GET_LIST_MONITORING_IKU_OPD_FAILED = "GET_LIST_MONITORING_IKU_OPD_FAILED"

const GET_LIST_MONITORING_RENJA_OPD_START = "GET_LIST_MONITORING_RENJA_OPD_START"
const GET_LIST_MONITORING_RENJA_OPD_SUCCESS = "GET_LIST_MONITORING_RENJA_OPD_SUCCESS"
const GET_LIST_MONITORING_RENJA_OPD_FAILED = "GET_LIST_MONITORING_RENJA_OPD_FAILED"

const GET_LIST_MONITORING_PK_OPD_START = "GET_LIST_MONITORING_PK_OPD_START"
const GET_LIST_MONITORING_PK_OPD_SUCCESS = "GET_LIST_MONITORING_PK_OPD_SUCCESS"
const GET_LIST_MONITORING_PK_OPD_FAILED = "GET_LIST_MONITORING_PK_OPD_FAILED"

const GET_LIST_MONITORING_RENCANAAKSI_OPD_START = "GET_LIST_MONITORING_RENCANAAKSI_OPD_START"
const GET_LIST_MONITORING_RENCANAAKSI_OPD_SUCCESS = "GET_LIST_MONITORING_RENCANAAKSI_OPD_SUCCESS"
const GET_LIST_MONITORING_RENCANAAKSI_OPD_FAILED = "GET_LIST_MONITORING_RENCANAAKSI_OPD_FAILED"

const GET_LIST_MONITORING_REALISASIRENAKSI_OPD_START = "GET_LIST_MONITORING_REALISASIRENAKSI_OPD_START"
const GET_LIST_MONITORING_REALISASIRENAKSI_OPD_SUCCESS = "GET_LIST_MONITORING_REALISASIRENAKSI_OPD_SUCCESS"
const GET_LIST_MONITORING_REALISASIRENAKSI_OPD_FAILED = "GET_LIST_MONITORING_REALISASIRENAKSI_OPD_FAILED"

const GET_LIST_MONITORING_DATAKINERJA_OPD_START = "GET_LIST_MONITORING_DATAKINERJA_OPD_START"
const GET_LIST_MONITORING_DATAKINERJA_OPD_SUCCESS = "GET_LIST_MONITORING_DATAKINERJA_OPD_SUCCESS"
const GET_LIST_MONITORING_DATAKINERJA_OPD_FAILED = "GET_LIST_MONITORING_DATAKINERJA_OPD_FAILED"

const GET_LIST_MONITORING_CAPAIANKINERJA_OPD_START = "GET_LIST_MONITORING_CAPAIANKINERJA_OPD_START"
const GET_LIST_MONITORING_CAPAIANKINERJA_OPD_SUCCESS = "GET_LIST_MONITORING_CAPAIANKINERJA_OPD_SUCCESS"
const GET_LIST_MONITORING_CAPAIANKINERJA_OPD_FAILED = "GET_LIST_MONITORING_CAPAIANKINERJA_OPD_FAILED"

export {

    SET_SELECTED_OPD, CLEAR_SELECTED_OPD,
    GET_LIST_MONITORING_POHONKINERJA_OPD_START,
    GET_LIST_MONITORING_POHONKINERJA_OPD_SUCCESS,
    GET_LIST_MONITORING_POHONKINERJA_OPD_FAILED,

    GET_LIST_MONITORING_CASCADING_OPD_START,
    GET_LIST_MONITORING_CASCADING_OPD_SUCCESS,
    GET_LIST_MONITORING_CASCADING_OPD_FAILED,

    GET_LIST_MONITORING_RENSTRA_OPD_START,
    GET_LIST_MONITORING_RENSTRA_OPD_SUCCESS,
    GET_LIST_MONITORING_RENSTRA_OPD_FAILED,

    GET_LIST_MONITORING_IKU_OPD_START,
    GET_LIST_MONITORING_IKU_OPD_SUCCESS,
    GET_LIST_MONITORING_IKU_OPD_FAILED,

    GET_LIST_MONITORING_RENJA_OPD_START,
    GET_LIST_MONITORING_RENJA_OPD_SUCCESS,
    GET_LIST_MONITORING_RENJA_OPD_FAILED,

    GET_LIST_MONITORING_PK_OPD_START,
    GET_LIST_MONITORING_PK_OPD_SUCCESS,
    GET_LIST_MONITORING_PK_OPD_FAILED,

    GET_LIST_MONITORING_RENCANAAKSI_OPD_START,
    GET_LIST_MONITORING_RENCANAAKSI_OPD_SUCCESS,
    GET_LIST_MONITORING_RENCANAAKSI_OPD_FAILED,

    GET_LIST_MONITORING_REALISASIRENAKSI_OPD_START,
    GET_LIST_MONITORING_REALISASIRENAKSI_OPD_SUCCESS,
    GET_LIST_MONITORING_REALISASIRENAKSI_OPD_FAILED,

    GET_LIST_MONITORING_DATAKINERJA_OPD_START,
    GET_LIST_MONITORING_DATAKINERJA_OPD_SUCCESS,
    GET_LIST_MONITORING_DATAKINERJA_OPD_FAILED,

    GET_LIST_MONITORING_CAPAIANKINERJA_OPD_START,
    GET_LIST_MONITORING_CAPAIANKINERJA_OPD_SUCCESS,
    GET_LIST_MONITORING_CAPAIANKINERJA_OPD_FAILED
    
}