const UPDATE_IKU_KDH_START = "UPDATE_IKU_KDH_START"
const UPDATE_IKU_KDH_SUCCESS = "UPDATE_IKU_KDH_SUCCESS"
const UPDATE_IKU_KDH_FAILED = "UPDATE_IKU_KDH_FAILED"

export {
    UPDATE_IKU_KDH_START,
    UPDATE_IKU_KDH_SUCCESS,
    UPDATE_IKU_KDH_FAILED
}