const GET_LIST_SASARANOPERASIONALOPD_START = "GET_LIST_SASARANOPERASIONALOPD_START"
const GET_LIST_SASARANOPERASIONALOPD_SUCCESS = "GET_LIST_SASARANOPERASIONALOPD_SUCCESS"
const GET_LIST_SASARANOPERASIONALOPD_FAILED = "GET_LIST_SASARANOPERASIONALOPD_FAILED"

const GET_REF_SASARANOPERASIONALOPD_START = "GET_REF_SASARANOPERASIONALOPD_START"
const GET_REF_SASARANOPERASIONALOPD_SUCCESS = "GET_REF_SASARANOPERASIONALOPD_SUCCESS"
const GET_REF_SASARANOPERASIONALOPD_FAILED = "GET_REF_SASARANOPERASIONALOPD_FAILED"

const CREATE_SASARANOPERASIONALOPD_START = "CREATE_SASARANOPERASIONALOPD_START"
const CREATE_SASARANOPERASIONALOPD_SUCCESS = "CREATE_SASARANOPERASIONALOPD_SUCCESS"
const CREATE_SASARANOPERASIONALOPD_FAILED = "CREATE_SASARANOPERASIONALOPD_FAILED"

const GET_SASARANOPERASIONALOPD_START = "GET_SASARANOPERASIONALOPD_START"
const GET_SASARANOPERASIONALOPD_SUCCESS = "GET_SASARANOPERASIONALOPD_SUCCESS"
const GET_SASARANOPERASIONALOPD_FAILED = "GET_SASARANOPERASIONALOPD_FAILED"

const DELETE_SASARANOPERASIONALOPD_START = "DELETE_SASARANOPERASIONALOPD_START"
const DELETE_SASARANOPERASIONALOPD_SUCCESS = "DELETE_SASARANOPERASIONALOPD_SUCCESS"
const DELETE_SASARANOPERASIONALOPD_FAILED = "DELETE_SASARANOPERASIONALOPD_FAILED"

export {
    GET_LIST_SASARANOPERASIONALOPD_START,
    GET_LIST_SASARANOPERASIONALOPD_SUCCESS,
    GET_LIST_SASARANOPERASIONALOPD_FAILED,

    GET_REF_SASARANOPERASIONALOPD_START,
    GET_REF_SASARANOPERASIONALOPD_SUCCESS,
    GET_REF_SASARANOPERASIONALOPD_FAILED,

    CREATE_SASARANOPERASIONALOPD_START,
    CREATE_SASARANOPERASIONALOPD_SUCCESS,
    CREATE_SASARANOPERASIONALOPD_FAILED,

    GET_SASARANOPERASIONALOPD_START,
    GET_SASARANOPERASIONALOPD_SUCCESS,
    GET_SASARANOPERASIONALOPD_FAILED,

    DELETE_SASARANOPERASIONALOPD_START,
    DELETE_SASARANOPERASIONALOPD_SUCCESS,
    DELETE_SASARANOPERASIONALOPD_FAILED
}