const GET_LIST_PKPEGAWAI_START = "GET_LIST_PKPEGAWAI_START"
const GET_LIST_PKPEGAWAI_SUCCESS = "GET_LIST_PKPEGAWAI_SUCCESS"
const GET_LIST_PKPEGAWAI_FAILED = "GET_LIST_PKPEGAWAI_FAILED"

const CREATE_PKPEGAWAI_START = "CREATE_PKPEGAWAI_START"
const CREATE_PKPEGAWAI_SUCCESS = "CREATE_PKPEGAWAI_SUCCESS"
const CREATE_PKPEGAWAI_FAILED = "CREATE_PKPEGAWAI_FAILED"

const CREATE_PROGRAM_PKPEGAWAI_START = "CREATE_PROGRAM_PKPEGAWAI_START"
const CREATE_PROGRAM_PKPEGAWAI_SUCCESS = "CREATE_PROGRAM_PKPEGAWAI_SUCCESS"
const CREATE_PROGRAM_PKPEGAWAI_FAILED = "CREATE_PROGRAM_PKPEGAWAI_FAILED"

const GET_LIST_PROGRAM_PKPEGAWAI_START = "GET_LIST_PROGRAM_PKPEGAWAI_START"
const GET_LIST_PROGRAM_PKPEGAWAI_SUCCESS = "GET_LIST_PROGRAM_PKPEGAWAI_SUCCESS"
const GET_LIST_PROGRAM_PKPEGAWAI_FAILED = "GET_LIST_PROGRAM_PKPEGAWAI_FAILED"

export {
    GET_LIST_PKPEGAWAI_START,
    GET_LIST_PKPEGAWAI_SUCCESS,
    GET_LIST_PKPEGAWAI_FAILED,

    CREATE_PKPEGAWAI_START,
    CREATE_PKPEGAWAI_SUCCESS,
    CREATE_PKPEGAWAI_FAILED,

    CREATE_PROGRAM_PKPEGAWAI_START,
    CREATE_PROGRAM_PKPEGAWAI_SUCCESS,
    CREATE_PROGRAM_PKPEGAWAI_FAILED,

    GET_LIST_PROGRAM_PKPEGAWAI_START,
    GET_LIST_PROGRAM_PKPEGAWAI_SUCCESS,
    GET_LIST_PROGRAM_PKPEGAWAI_FAILED
}