const GET_LIST_RKPDKDH_START = "GET_LIST_RKPDKDH_START"
const GET_LIST_RKPDKDH_SUCCESS = "GET_LIST_RKPDKDH_SUCCESS"
const GET_LIST_RKPDKDH_FAILED = "GET_LIST_RKPDKDH_FAILED"

const CREATE_RKPDKDH_START = "CREATE_RKPDKDH_START"
const CREATE_RKPDKDH_SUCCESS = "CREATE_RKPDKDH_SUCCESS"
const CREATE_RKPDKDH_FAILED = "CREATE_RKPDKDH_FAILED"

const CREATE_PROGRAM_RKPD_KDH_START = "CREATE_PROGRAM_RKPD_KDH_START"
const CREATE_PROGRAM_RKPD_KDH_SUCCESS = "CREATE_PROGRAM_RKPD_KDH_SUCCESS"
const CREATE_PROGRAM_RKPD_KDH_FAILED = "CREATE_PROGRAM_RKPD_KDH_FAILED"

const GET_LIST_PROGRAM_RKPD_KDH_START = "GET_LIST_PROGRAM_RKPD_KDH_START"
const GET_LIST_PROGRAM_RKPD_KDH_SUCCESS = "GET_LIST_PROGRAM_RKPD_KDH_SUCCESS"
const GET_LIST_PROGRAM_RKPD_KDH_FAILED = "GET_LIST_PROGRAM_RKPD_KDH_FAILED"

export {
    GET_LIST_RKPDKDH_START,
    GET_LIST_RKPDKDH_SUCCESS,
    GET_LIST_RKPDKDH_FAILED,

    CREATE_RKPDKDH_START,
    CREATE_RKPDKDH_SUCCESS,
    CREATE_RKPDKDH_FAILED,

    CREATE_PROGRAM_RKPD_KDH_START,
    CREATE_PROGRAM_RKPD_KDH_SUCCESS,
    CREATE_PROGRAM_RKPD_KDH_FAILED,

    GET_LIST_PROGRAM_RKPD_KDH_START,
    GET_LIST_PROGRAM_RKPD_KDH_SUCCESS,
    GET_LIST_PROGRAM_RKPD_KDH_FAILED
}