const GET_LIST_CASCADINGOPD_START = "GET_LIST_CASCADINGOPD_START"
const GET_LIST_CASCADINGOPD_SUCCESS = "GET_LIST_CASCADINGOPD_SUCCESS"
const GET_LIST_CASCADINGOPD_FAILED = "GET_LIST_CASCADINGOPD_FAILED"

const CREATE_CASCADINGOPD_START = "CREATE_CASCADINGOPD_START"
const CREATE_CASCADINGOPD_SUCCESS = "CREATE_CASCADINGOPD_SUCCESS"
const CREATE_CASCADINGOPD_FAILED = "CREATE_CASCADINGOPD_FAILED"

export {
    GET_LIST_CASCADINGOPD_START,
    GET_LIST_CASCADINGOPD_SUCCESS,
    GET_LIST_CASCADINGOPD_FAILED,

    CREATE_CASCADINGOPD_START,
    CREATE_CASCADINGOPD_SUCCESS,
    CREATE_CASCADINGOPD_FAILED
}