const GET_LIST_RENJAOPD_START = "GET_LIST_RENJAOPD_START"
const GET_LIST_RENJAOPD_SUCCESS = "GET_LIST_RENJAOPD_SUCCESS"
const GET_LIST_RENJAOPD_FAILED = "GET_LIST_RENJAOPD_FAILED"

const CREATE_RENJAOPD_START = "CREATE_RENJAOPD_START"
const CREATE_RENJAOPD_SUCCESS = "CREATE_RENJAOPD_SUCCESS"
const CREATE_RENJAOPD_FAILED = "CREATE_RENJAOPD_FAILED"

const CREATE_PROGRAM_RENJAOPD_START = "CREATE_PROGRAM_RENJAOPD_START"
const CREATE_PROGRAM_RENJAOPD_SUCCESS = "CREATE_PROGRAM_RENJAOPD_SUCCESS"
const CREATE_PROGRAM_RENJAOPD_FAILED = "CREATE_PROGRAM_RENJAOPD_FAILED"

const GET_LIST_PROGRAM_RENJAOPD_START = "GET_LIST_PROGRAM_RENJAOPD_START"
const GET_LIST_PROGRAM_RENJAOPD_SUCCESS = "GET_LIST_PROGRAM_RENJAOPD_SUCCESS"
const GET_LIST_PROGRAM_RENJAOPD_FAILED = "GET_LIST_PROGRAM_RENJAOPD_FAILED"

export {
    GET_LIST_RENJAOPD_START,
    GET_LIST_RENJAOPD_SUCCESS,
    GET_LIST_RENJAOPD_FAILED,

    CREATE_RENJAOPD_START,
    CREATE_RENJAOPD_SUCCESS,
    CREATE_RENJAOPD_FAILED,

    CREATE_PROGRAM_RENJAOPD_START,
    CREATE_PROGRAM_RENJAOPD_SUCCESS,
    CREATE_PROGRAM_RENJAOPD_FAILED,

    GET_LIST_PROGRAM_RENJAOPD_START,
    GET_LIST_PROGRAM_RENJAOPD_SUCCESS,
    GET_LIST_PROGRAM_RENJAOPD_FAILED
}