const GET_LIST_REALISASI_RENAKSIKDH_START = "GET_LIST_REALISASI_RENAKSIKDH_START"
const GET_LIST_REALISASI_RENAKSIKDH_SUCCESS = "GET_LIST_REALISASI_RENAKSIKDH_SUCCESS"
const GET_LIST_REALISASI_RENAKSIKDH_FAILED = "GET_LIST_REALISASI_RENAKSIKDH_FAILED"

const CREATE_REALISASI_RENAKSIKDH_START = "CREATE_REALISASI_RENAKSIKDH_START"
const CREATE_REALISASI_RENAKSIKDH_SUCCESS = "CREATE_REALISASI_RENAKSIKDH_SUCCESS"
const CREATE_REALISASI_RENAKSIKDH_FAILED = "CREATE_REALISASI_RENAKSIKDH_FAILED"

const GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_START = "GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_START"
const GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_SUCCESS = "GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_SUCCESS"
const GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_FAILED = "GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_FAILED"

const CREATE_REALISASI_RENAKSIKDH_LANGKAH_START = "CREATE_REALISASI_RENAKSIKDH_LANGKAH_START"
const CREATE_REALISASI_RENAKSIKDH_LANGKAH_SUCCESS = "CREATE_REALISASI_RENAKSIKDH_LANGKAH_SUCCESS"
const CREATE_REALISASI_RENAKSIKDH_LANGKAH_FAILED = "CREATE_REALISASI_RENAKSIKDH_LANGKAH_FAILED"

export {
    GET_LIST_REALISASI_RENAKSIKDH_START,
    GET_LIST_REALISASI_RENAKSIKDH_SUCCESS,
    GET_LIST_REALISASI_RENAKSIKDH_FAILED,

    GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_START,
    GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_SUCCESS,
    GET_LIST_REALISASI_RENAKSIKDH_LANGKAH_FAILED,

    CREATE_REALISASI_RENAKSIKDH_START,
    CREATE_REALISASI_RENAKSIKDH_SUCCESS,
    CREATE_REALISASI_RENAKSIKDH_FAILED,

    CREATE_REALISASI_RENAKSIKDH_LANGKAH_START,
    CREATE_REALISASI_RENAKSIKDH_LANGKAH_SUCCESS,
    CREATE_REALISASI_RENAKSIKDH_LANGKAH_FAILED
}