const GET_LIST_PKKDH_START = "GET_LIST_PKKDH_START"
const GET_LIST_PKKDH_SUCCESS = "GET_LIST_PKKDH_SUCCESS"
const GET_LIST_PKKDH_FAILED = "GET_LIST_PKKDH_FAILED"

const CREATE_PKKDH_START = "CREATE_PKKDH_START"
const CREATE_PKKDH_SUCCESS = "CREATE_PKKDH_SUCCESS"
const CREATE_PKKDH_FAILED = "CREATE_PKKDH_FAILED"

const CREATE_PROGRAM_PKKDH_START = "CREATE_PROGRAM_PKKDH_START"
const CREATE_PROGRAM_PKKDH_SUCCESS = "CREATE_PROGRAM_PKKDH_SUCCESS"
const CREATE_PROGRAM_PKKDH_FAILED = "CREATE_PROGRAM_PKKDH_FAILED"

const GET_LIST_PROGRAM_PKKDH_START = "GET_LIST_PROGRAM_PKKDH_START"
const GET_LIST_PROGRAM_PKKDH_SUCCESS = "GET_LIST_PROGRAM_PKKDH_SUCCESS"
const GET_LIST_PROGRAM_PKKDH_FAILED = "GET_LIST_PROGRAM_PKKDH_FAILED"

export {
    GET_LIST_PKKDH_START,
    GET_LIST_PKKDH_SUCCESS,
    GET_LIST_PKKDH_FAILED,

    CREATE_PKKDH_START,
    CREATE_PKKDH_SUCCESS,
    CREATE_PKKDH_FAILED,

    CREATE_PROGRAM_PKKDH_START,
    CREATE_PROGRAM_PKKDH_SUCCESS,
    CREATE_PROGRAM_PKKDH_FAILED,

    GET_LIST_PROGRAM_PKKDH_START,
    GET_LIST_PROGRAM_PKKDH_SUCCESS,
    GET_LIST_PROGRAM_PKKDH_FAILED
}