const GET_LIST_RENAKSIKDH_START = "GET_LIST_RENAKSIKDH_START"
const GET_LIST_RENAKSIKDH_SUCCESS = "GET_LIST_RENAKSIKDH_SUCCESS"
const GET_LIST_RENAKSIKDH_FAILED = "GET_LIST_RENAKSIKDH_FAILED"

const CREATE_RENAKSIKDH_START = "CREATE_RENAKSIKDH_START"
const CREATE_RENAKSIKDH_SUCCESS = "CREATE_RENAKSIKDH_SUCCESS"
const CREATE_RENAKSIKDH_FAILED = "CREATE_RENAKSIKDH_FAILED"

const GET_LIST_RENAKSIKDH_LANGKAH_START = "GET_LIST_RENAKSIKDH_LANGKAH_START"
const GET_LIST_RENAKSIKDH_LANGKAH_SUCCESS = "GET_LIST_RENAKSIKDH_LANGKAH_SUCCESS"
const GET_LIST_RENAKSIKDH_LANGKAH_FAILED = "GET_LIST_RENAKSIKDH_LANGKAH_FAILED"

const CREATE_RENAKSIKDH_LANGKAH_START = "CREATE_RENAKSIKDH_LANGKAH_START"
const CREATE_RENAKSIKDH_LANGKAH_SUCCESS = "CREATE_RENAKSIKDH_LANGKAH_SUCCESS"
const CREATE_RENAKSIKDH_LANGKAH_FAILED = "CREATE_RENAKSIKDH_LANGKAH_FAILED"

const UPDATE_RENAKSIKDH_LANGKAH_START = "UPDATE_RENAKSIKDH_LANGKAH_START"
const UPDATE_RENAKSIKDH_LANGKAH_SUCCESS = "UPDATE_RENAKSIKDH_LANGKAH_SUCCESS"
const UPDATE_RENAKSIKDH_LANGKAH_FAILED = "UPDATE_RENAKSIKDH_LANGKAH_FAILED"

const DELETE_RENAKSIKDH_LANGKAH_START = "DELETE_RENAKSIKDH_LANGKAH_START"
const DELETE_RENAKSIKDH_LANGKAH_SUCCESS = "DELETE_RENAKSIKDH_LANGKAH_SUCCESS"
const DELETE_RENAKSIKDH_LANGKAH_FAILED = "DELETE_RENAKSIKDH_LANGKAH_FAILED"

export {
    GET_LIST_RENAKSIKDH_START,
    GET_LIST_RENAKSIKDH_SUCCESS,
    GET_LIST_RENAKSIKDH_FAILED,

    CREATE_RENAKSIKDH_START,
    CREATE_RENAKSIKDH_SUCCESS,
    CREATE_RENAKSIKDH_FAILED,

    GET_LIST_RENAKSIKDH_LANGKAH_START,
    GET_LIST_RENAKSIKDH_LANGKAH_SUCCESS,
    GET_LIST_RENAKSIKDH_LANGKAH_FAILED,

    CREATE_RENAKSIKDH_LANGKAH_START,
    CREATE_RENAKSIKDH_LANGKAH_SUCCESS,
    CREATE_RENAKSIKDH_LANGKAH_FAILED,

    UPDATE_RENAKSIKDH_LANGKAH_START,
    UPDATE_RENAKSIKDH_LANGKAH_SUCCESS,
    UPDATE_RENAKSIKDH_LANGKAH_FAILED,

    DELETE_RENAKSIKDH_LANGKAH_START,
    DELETE_RENAKSIKDH_LANGKAH_SUCCESS,
    DELETE_RENAKSIKDH_LANGKAH_FAILED
}