const GET_LIST_DATAMASTERSATUAN_START       = "GET_LIST_DATAMASTERSATUAN_START"
const GET_LIST_DATAMASTERSATUAN_SUCCESS     = "GET_LIST_DATAMASTERSATUAN_SUCCESS"
const GET_LIST_DATAMASTERSATUAN_FAILED      = "GET_LIST_DATAMASTERSATUAN_FAILED"

const CREATE_DATAMASTERSATUAN_START         = "CREATE_DATAMASTERSATUAN_START"
const CREATE_DATAMASTERSATUAN_SUCCESS       = "CREATE_DATAMASTERSATUAN_SUCCESS"
const CREATE_DATAMASTERSATUAN_FAILED        = "CREATE_DATAMASTERSATUAN_FAILED"

const GET_DATAMASTERSATUAN_START            = "GET_DATAMASTERSATUAN_START"
const GET_DATAMASTERSATUAN_SUCCESS          = "GET_DATAMASTERSATUAN_SUCCESS"
const GET_DATAMASTERSATUAN_FAILED           = "GET_DATAMASTERSATUAN_FAILED"

const UPDATE_DATAMASTERSATUAN_START         = "UPDATE_DATAMASTERSATUAN_START"
const UPDATE_DATAMASTERSATUAN_SUCCESS       = "UPDATE_DATAMASTERSATUAN_SUCCESS"
const UPDATE_DATAMASTERSATUAN_FAILED        = "UPDATE_DATAMASTERSATUAN_FAILED"

const DELETE_DATAMASTERSATUAN_START         = "DELETE_DATAMASTERSATUAN_START"
const DELETE_DATAMASTERSATUAN_SUCCESS       = "DELETE_DATAMASTERSATUAN_SUCCESS"
const DELETE_DATAMASTERSATUAN_FAILED        = "DELETE_DATAMASTERSATUAN_FAILED"

const GET_OPTIONSSATUAN_START = "GET_OPTIONSSATUAN_START"
const GET_OPTIONSSATUAN_SUCCESS = "GET_OPTIONSSATUAN_SUCCESS"
const GET_OPTIONSSATUAN_FAILED = "GET_OPTIONSSATUAN_FAILED"

export {
    GET_LIST_DATAMASTERSATUAN_START,
    GET_LIST_DATAMASTERSATUAN_SUCCESS,
    GET_LIST_DATAMASTERSATUAN_FAILED,

    CREATE_DATAMASTERSATUAN_START,
    CREATE_DATAMASTERSATUAN_SUCCESS,
    CREATE_DATAMASTERSATUAN_FAILED,

    GET_DATAMASTERSATUAN_START,
    GET_DATAMASTERSATUAN_SUCCESS,
    GET_DATAMASTERSATUAN_FAILED,

    UPDATE_DATAMASTERSATUAN_START,
    UPDATE_DATAMASTERSATUAN_SUCCESS,
    UPDATE_DATAMASTERSATUAN_FAILED,

    DELETE_DATAMASTERSATUAN_START,
    DELETE_DATAMASTERSATUAN_SUCCESS,
    DELETE_DATAMASTERSATUAN_FAILED,

    GET_OPTIONSSATUAN_START,
    GET_OPTIONSSATUAN_SUCCESS,
    GET_OPTIONSSATUAN_FAILED
}