const GET_LIST_RENAKSIPEGAWAI_START = "GET_LIST_RENAKSIPEGAWAI_START"
const GET_LIST_RENAKSIPEGAWAI_SUCCESS = "GET_LIST_RENAKSIPEGAWAI_SUCCESS"
const GET_LIST_RENAKSIPEGAWAI_FAILED = "GET_LIST_RENAKSIPEGAWAI_FAILED"

const CREATE_RENAKSIPEGAWAI_START = "CREATE_RENAKSIPEGAWAI_START"
const CREATE_RENAKSIPEGAWAI_SUCCESS = "CREATE_RENAKSIPEGAWAI_SUCCESS"
const CREATE_RENAKSIPEGAWAI_FAILED = "CREATE_RENAKSIPEGAWAI_FAILED"

const GET_LIST_RENAKSIPEGAWAI_LANGKAH_START = "GET_LIST_RENAKSIPEGAWAI_LANGKAH_START"
const GET_LIST_RENAKSIPEGAWAI_LANGKAH_SUCCESS = "GET_LIST_RENAKSIPEGAWAI_LANGKAH_SUCCESS"
const GET_LIST_RENAKSIPEGAWAI_LANGKAH_FAILED = "GET_LIST_RENAKSIPEGAWAI_LANGKAH_FAILED"

const CREATE_RENAKSIPEGAWAI_LANGKAH_START = "CREATE_RENAKSIPEGAWAI_LANGKAH_START"
const CREATE_RENAKSIPEGAWAI_LANGKAH_SUCCESS = "CREATE_RENAKSIPEGAWAI_LANGKAH_SUCCESS"
const CREATE_RENAKSIPEGAWAI_LANGKAH_FAILED = "CREATE_RENAKSIPEGAWAI_LANGKAH_FAILED"

const UPDATE_RENAKSIPEGAWAI_LANGKAH_START = "UPDATE_RENAKSIPEGAWAI_LANGKAH_START"
const UPDATE_RENAKSIPEGAWAI_LANGKAH_SUCCESS = "UPDATE_RENAKSIPEGAWAI_LANGKAH_SUCCESS"
const UPDATE_RENAKSIPEGAWAI_LANGKAH_FAILED = "UPDATE_RENAKSIPEGAWAI_LANGKAH_FAILED"

const DELETE_RENAKSIPEGAWAI_LANGKAH_START = "DELETE_RENAKSIPEGAWAI_LANGKAH_START"
const DELETE_RENAKSIPEGAWAI_LANGKAH_SUCCESS = "DELETE_RENAKSIPEGAWAI_LANGKAH_SUCCESS"
const DELETE_RENAKSIPEGAWAI_LANGKAH_FAILED = "DELETE_RENAKSIPEGAWAI_LANGKAH_FAILED"

export {
    GET_LIST_RENAKSIPEGAWAI_START,
    GET_LIST_RENAKSIPEGAWAI_SUCCESS,
    GET_LIST_RENAKSIPEGAWAI_FAILED,

    CREATE_RENAKSIPEGAWAI_START,
    CREATE_RENAKSIPEGAWAI_SUCCESS,
    CREATE_RENAKSIPEGAWAI_FAILED,

    GET_LIST_RENAKSIPEGAWAI_LANGKAH_START,
    GET_LIST_RENAKSIPEGAWAI_LANGKAH_SUCCESS,
    GET_LIST_RENAKSIPEGAWAI_LANGKAH_FAILED,

    CREATE_RENAKSIPEGAWAI_LANGKAH_START,
    CREATE_RENAKSIPEGAWAI_LANGKAH_SUCCESS,
    CREATE_RENAKSIPEGAWAI_LANGKAH_FAILED,

    UPDATE_RENAKSIPEGAWAI_LANGKAH_START,
    UPDATE_RENAKSIPEGAWAI_LANGKAH_SUCCESS,
    UPDATE_RENAKSIPEGAWAI_LANGKAH_FAILED,

    DELETE_RENAKSIPEGAWAI_LANGKAH_START,
    DELETE_RENAKSIPEGAWAI_LANGKAH_SUCCESS,
    DELETE_RENAKSIPEGAWAI_LANGKAH_FAILED
}