const GET_LIST_VISIKDH_START = "GET_LIST_VISIKDH_START"
const GET_LIST_VISIKDH_SUCCESS = "GET_LIST_VISIKDH_SUCCESS"
const GET_LIST_VISIKDH_FAILED = "GET_LIST_VISIKDH_FAILED"

const CREATE_VISIKDH_START = "CREATE_VISIKDH_START"
const CREATE_VISIKDH_SUCCESS = "CREATE_VISIKDH_SUCCESS"
const CREATE_VISIKDH_FAILED = "CREATE_VISIKDH_FAILED"

const GET_VISIKDH_START = "GET_VISIKDH_START"
const GET_VISIKDH_SUCCESS = "GET_VISIKDH_SUCCESS"
const GET_VISIKDH_FAILED = "GET_VISIKDH_FAILED"

const UPDATE_VISIKDH_START = "UPDATE_VISIKDH_START"
const UPDATE_VISIKDH_SUCCESS = "UPDATE_VISIKDH_SUCCESS"
const UPDATE_VISIKDH_FAILED = "UPDATE_VISIKDH_FAILED"

const DELETE_VISIKDH_START = "DELETE_VISIKDH_START"
const DELETE_VISIKDH_SUCCESS = "DELETE_VISIKDH_SUCCESS"
const DELETE_VISIKDH_FAILED = "DELETE_VISIKDH_FAILED"


export {
    GET_LIST_VISIKDH_START,
    GET_LIST_VISIKDH_SUCCESS,
    GET_LIST_VISIKDH_FAILED,

    CREATE_VISIKDH_START,
    CREATE_VISIKDH_SUCCESS,
    CREATE_VISIKDH_FAILED,

    GET_VISIKDH_START,
    GET_VISIKDH_SUCCESS,
    GET_VISIKDH_FAILED,

    UPDATE_VISIKDH_START,
    UPDATE_VISIKDH_SUCCESS,
    UPDATE_VISIKDH_FAILED,

    DELETE_VISIKDH_START,
    DELETE_VISIKDH_SUCCESS,
    DELETE_VISIKDH_FAILED
}