const GET_LIST_REALISASI_RENAKSIOPD_START = "GET_LIST_REALISASI_RENAKSIOPD_START"
const GET_LIST_REALISASI_RENAKSIOPD_SUCCESS = "GET_LIST_REALISASI_RENAKSIOPD_SUCCESS"
const GET_LIST_REALISASI_RENAKSIOPD_FAILED = "GET_LIST_REALISASI_RENAKSIOPD_FAILED"

const CREATE_REALISASI_RENAKSIOPD_START = "CREATE_REALISASI_RENAKSIOPD_START"
const CREATE_REALISASI_RENAKSIOPD_SUCCESS = "CREATE_REALISASI_RENAKSIOPD_SUCCESS"
const CREATE_REALISASI_RENAKSIOPD_FAILED = "CREATE_REALISASI_RENAKSIOPD_FAILED"

const GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_START = "GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_START"
const GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_SUCCESS = "GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_SUCCESS"
const GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_FAILED = "GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_FAILED"

const CREATE_REALISASI_RENAKSIOPD_LANGKAH_START = "CREATE_REALISASI_RENAKSIOPD_LANGKAH_START"
const CREATE_REALISASI_RENAKSIOPD_LANGKAH_SUCCESS = "CREATE_REALISASI_RENAKSIOPD_LANGKAH_SUCCESS"
const CREATE_REALISASI_RENAKSIOPD_LANGKAH_FAILED = "CREATE_REALISASI_RENAKSIOPD_LANGKAH_FAILED"

export {
    GET_LIST_REALISASI_RENAKSIOPD_START,
    GET_LIST_REALISASI_RENAKSIOPD_SUCCESS,
    GET_LIST_REALISASI_RENAKSIOPD_FAILED,

    GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_START,
    GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_SUCCESS,
    GET_LIST_REALISASI_RENAKSIOPD_LANGKAH_FAILED,

    CREATE_REALISASI_RENAKSIOPD_START,
    CREATE_REALISASI_RENAKSIOPD_SUCCESS,
    CREATE_REALISASI_RENAKSIOPD_FAILED,

    CREATE_REALISASI_RENAKSIOPD_LANGKAH_START,
    CREATE_REALISASI_RENAKSIOPD_LANGKAH_SUCCESS,
    CREATE_REALISASI_RENAKSIOPD_LANGKAH_FAILED
}