const UPDATE_IKU_OPD_START = "UPDATE_IKU_OPD_START"
const UPDATE_IKU_OPD_SUCCESS = "UPDATE_IKU_OPD_SUCCESS"
const UPDATE_IKU_OPD_FAILED = "UPDATE_IKU_OPD_FAILED"

const GET_LIST_IKU_OPD_START = "GET_LIST_IKU_OPD_START"
const GET_LIST_IKU_OPD_SUCCESS = "GET_LIST_IKU_OPD_SUCCESS"
const GET_LIST_IKU_OPD_FAILED = "GET_LIST_IKU_OPD_FAILED"

export {
    UPDATE_IKU_OPD_START,
    UPDATE_IKU_OPD_SUCCESS,
    UPDATE_IKU_OPD_FAILED,

    GET_LIST_IKU_OPD_START,
    GET_LIST_IKU_OPD_SUCCESS,
    GET_LIST_IKU_OPD_FAILED
}