import * as types from './types'

const GET_LIST_ATASAN_START = "GET_LIST_ATASAN_START"
const GET_LIST_ATASAN_SUCCESS = "GET_LIST_ATASAN_SUCCESS"
const GET_LIST_ATASAN_FAILED = "GET_LIST_ATASAN_FAILED"

const CREATE_ATASAN_START = "CREATE_ATASAN_START"
const CREATE_ATASAN_SUCCESS = "CREATE_ATASAN_SUCCESS"
const CREATE_ATASAN_FAILED = "CREATE_ATASAN_FAILED"

export {
    GET_LIST_ATASAN_START,
    GET_LIST_ATASAN_SUCCESS,
    GET_LIST_ATASAN_FAILED,

    CREATE_ATASAN_START,
    CREATE_ATASAN_SUCCESS,
    CREATE_ATASAN_FAILED
}