const GET_LIST_INDIKATORKDH_START        = "GET_LIST_INDIKATORKDH_START"
const GET_LIST_INDIKATORKDH_SUCCESS      = "GET_LIST_INDIKATORKDH_SUCCESS"
const GET_LIST_INDIKATORKDH_FAILED       = "GET_LIST_INDIKATORKDH_FAILED"

const CREATE_INDIKATORKDH_START          = "CREATE_INDIKATORKDH_START"
const CREATE_INDIKATORKDH_SUCCESS        = "CREATE_INDIKATORKDH_SUCCESS"
const CREATE_INDIKATORKDH_FAILED         = "CREATE_INDIKATORKDH_FAILED"

const GET_INDIKATORKDH_START             = "GET_INDIKATORKDH_START"
const GET_INDIKATORKDH_SUCCESS           = "GET_INDIKATORKDH_SUCCESS"
const GET_INDIKATORKDH_FAILED            = "GET_INDIKATORKDH_FAILED"

const UPDATE_INDIKATORKDH_START          = "UPDATE_INDIKATORKDH_START"
const UPDATE_INDIKATORKDH_SUCCESS        = "UPDATE_INDIKATORKDH_SUCCESS"
const UPDATE_INDIKATORKDH_FAILED         = "UPDATE_INDIKATORKDH_FAILED"

const DELETE_INDIKATORKDH_START          = "DELETE_INDIKATORKDH_START"
const DELETE_INDIKATORKDH_SUCCESS        = "DELETE_INDIKATORKDH_SUCCESS"
const DELETE_INDIKATORKDH_FAILED         = "DELETE_INDIKATORKDH_FAILED"

const UPLOAD_FORMULA_PERHITUNGAN_KDH_START = "UPLOAD_FORMULA_PERHITUNGAN_KDH_START"
const UPLOAD_FORMULA_PERHITUNGAN_KDH_SUCCESS = "UPLOAD_FORMULA_PERHITUNGAN_KDH_SUCCESS"
const UPLOAD_FORMULA_PERHITUNGAN_KDH_FAILED = "UPLOAD_FORMULA_PERHITUNGAN_KDH_FAILED"

export {
    GET_LIST_INDIKATORKDH_START, GET_LIST_INDIKATORKDH_SUCCESS, GET_LIST_INDIKATORKDH_FAILED,
    CREATE_INDIKATORKDH_START, CREATE_INDIKATORKDH_SUCCESS, CREATE_INDIKATORKDH_FAILED,
    GET_INDIKATORKDH_START, GET_INDIKATORKDH_SUCCESS, GET_INDIKATORKDH_FAILED,
    UPDATE_INDIKATORKDH_START, UPDATE_INDIKATORKDH_SUCCESS, UPDATE_INDIKATORKDH_FAILED,
    DELETE_INDIKATORKDH_START, DELETE_INDIKATORKDH_SUCCESS, DELETE_INDIKATORKDH_FAILED,
    UPLOAD_FORMULA_PERHITUNGAN_KDH_START, UPLOAD_FORMULA_PERHITUNGAN_KDH_SUCCESS, UPLOAD_FORMULA_PERHITUNGAN_KDH_FAILED
}