const GET_LIST_PEGAWAI_START   = "GET_LIST_PEGAWAI_START"
const GET_LIST_PEGAWAI_SUCCESS = "GET_LIST_PEGAWAI_SUCCESS"
const GET_LIST_PEGAWAI_FAILED  = "GET_LIST_PEGAWAI_FAILED"

const CREATE_PEGAWAI_START     = "CREATE_PEGAWAI_START"
const CREATE_PEGAWAI_SUCCESS   = "CREATE_PEGAWAI_SUCCESS"
const CREATE_PEGAWAI_FAILED    = "CREATE_PEGAWAI_FAILED"

const GET_PEGAWAI_START        = "GET_PEGAWAI_START"
const GET_PEGAWAI_SUCCESS      = "GET_PEGAWAI_SUCCESS"
const GET_PEGAWAI_FAILED       = "GET_PEGAWAI_FAILED"

const UPDATE_PEGAWAI_START     = "UPDATE_PEGAWAI_START"
const UPDATE_PEGAWAI_SUCCESS   = "UPDATE_PEGAWAI_SUCCESS"
const UPDATE_PEGAWAI_FAILED    = "UPDATE_PEGAWAI_FAILED"

const DELETE_PEGAWAI_START     = "DELETE_PEGAWAI_START"
const DELETE_PEGAWAI_SUCCESS   = "DELETE_PEGAWAI_SUCCESS"
const DELETE_PEGAWAI_FAILED    = "DELETE_PEGAWAI_FAILED"

export {
    GET_LIST_PEGAWAI_START, GET_LIST_PEGAWAI_SUCCESS, GET_LIST_PEGAWAI_FAILED,
    CREATE_PEGAWAI_START, CREATE_PEGAWAI_SUCCESS, CREATE_PEGAWAI_FAILED,
    GET_PEGAWAI_START, GET_PEGAWAI_SUCCESS, GET_PEGAWAI_FAILED,
    UPDATE_PEGAWAI_START, UPDATE_PEGAWAI_SUCCESS, UPDATE_PEGAWAI_FAILED,
    DELETE_PEGAWAI_START, DELETE_PEGAWAI_SUCCESS, DELETE_PEGAWAI_FAILED,
}
