const GET_LIST_RPJMD_START = "GET_LIST_RPJMD_START"
const GET_LIST_RPJMD_SUCCESS = "GET_LIST_RPJMD_SUCCESS"
const GET_LIST_RPJMD_FAILED = "GET_LIST_RPJMD_FAILED"

const CREATE_TARGET_RPJMD_KDH_START = "CREATE_TARGET_RPJMD_KDH_START"
const CREATE_TARGET_RPJMD_KDH_SUCCESS = "CREATE_TARGET_RPJMD_KDH_SUCCESS"
const CREATE_TARGET_RPJMD_KDH_FAILED = "CREATE_TARGET_RPJMD_KDH_FAILED"

export {
    GET_LIST_RPJMD_START,
    GET_LIST_RPJMD_SUCCESS,
    GET_LIST_RPJMD_FAILED,

    CREATE_TARGET_RPJMD_KDH_START,
    CREATE_TARGET_RPJMD_KDH_SUCCESS,
    CREATE_TARGET_RPJMD_KDH_FAILED
}