const GET_PROGRAM_ANGGARAN_START    = "GET_PROGRAM_ANGGARAN_START"
const GET_PROGRAM_ANGGARAN_SUCCESS  = "GET_PROGRAM_ANGGARAN_SUCCESS"
const GET_PROGRAM_ANGGARAN_FAILED   = "GET_PROGRAM_ANGGARAN_FAILED"

export {
    GET_PROGRAM_ANGGARAN_START, GET_PROGRAM_ANGGARAN_SUCCESS, GET_PROGRAM_ANGGARAN_FAILED
}