const AUTH_LOADING = 'AUTH_LOADING'
const AUTH_SUCCESS = 'AUTH_SUCESSS'
const AUTH_FAILED = 'AUTH_FAILED'
const AUTH_DESTROY = 'AUTH_DESTROY'

const GET_MYROLES_START = "GET_MYROLES_START"
const GET_MYROLES_SUCCESS = "GET_MYROLES_SUCCESS"
const GET_MYROLES_FAILED = "GET_MYROLES_FAILED"

export {
    AUTH_LOADING,
    AUTH_SUCCESS,
    AUTH_FAILED,
    AUTH_DESTROY,

    GET_MYROLES_START, GET_MYROLES_SUCCESS, GET_MYROLES_FAILED
}
