const GET_LIST_MISIKDH_START        = "GET_LIST_MISIKDH_START"
const GET_LIST_MISIKDH_SUCCESS      = "GET_LIST_MISIKDH_SUCCESS"
const GET_LIST_MISIKDH_FAILED       = "GET_LIST_MISIKDH_FAILED"

const CREATE_MISIKDH_START          = "CREATE_MISIKDH_START"
const CREATE_MISIKDH_SUCCESS        = "CREATE_MISIKDH_SUCCESS"
const CREATE_MISIKDH_FAILED         = "CREATE_MISIKDH_FAILED"

const GET_MISIKDH_START             = "GET_MISIKDH_START"
const GET_MISIKDH_SUCCESS           = "GET_MISIKDH_SUCCESS"
const GET_MISIKDH_FAILED            = "GET_MISIKDH_FAILED"

const UPDATE_MISIKDH_START          = "UPDATE_MISIKDH_START"
const UPDATE_MISIKDH_SUCCESS        = "UPDATE_MISIKDH_SUCCESS"
const UPDATE_MISIKDH_FAILED         = "UPDATE_MISIKDH_FAILED"

const DELETE_MISIKDH_START          = "DELETE_MISIKDH_START"
const DELETE_MISIKDH_SUCCESS        = "DELETE_MISIKDH_SUCCESS"
const DELETE_MISIKDH_FAILED         = "DELETE_MISIKDH_FAILED"

export {
    GET_LIST_MISIKDH_START, GET_LIST_MISIKDH_SUCCESS, GET_LIST_MISIKDH_FAILED,
    CREATE_MISIKDH_START, CREATE_MISIKDH_SUCCESS, CREATE_MISIKDH_FAILED,
    GET_MISIKDH_START, GET_MISIKDH_SUCCESS, GET_MISIKDH_FAILED,
    UPDATE_MISIKDH_START, UPDATE_MISIKDH_SUCCESS, UPDATE_MISIKDH_FAILED,
    DELETE_MISIKDH_START, DELETE_MISIKDH_SUCCESS, DELETE_MISIKDH_FAILED
}