const GET_LIST_PERIODE_SKP_START = "GET_LIST_PERIODE_SKP_START"
const GET_LIST_PERIODE_SKP_SUCCESS = "GET_LIST_PERIODE_SKP_SUCCESS"
const GET_LIST_PERIODE_SKP_FAILED = "GET_LIST_PERIODE_SKP_FAILED"

const CREATE_PERIODE_SKP_START = "CREATE_PERIODE_SKP_START"
const CREATE_PERIODE_SKP_SUCCESS = "CREATE_PERIODE_SKP_SUCCESS"
const CREATE_PERIODE_SKP_FAILED = "CREATE_PERIODE_SKP_FAILED"

const GET_PERIODE_SKP_START = "GET_PERIODE_SKP_START"
const GET_PERIODE_SKP_SUCCESS = "GET_PERIODE_SKP_SUCCESS"
const GET_PERIODE_SKP_FAILED = "GET_PERIODE_SKP_FAILED"

const GET_LIST_SASARAN_YANG_DIAMPU_START = "GET_LIST_SASARAN_YANG_DIAMPU_START"
const GET_LIST_SASARAN_YANG_DIAMPU_SUCCESS = "GET_LIST_SASARAN_YANG_DIAMPU_SUCCESS"
const GET_LIST_SASARAN_YANG_DIAMPU_FAILED = "GET_LIST_SASARAN_YANG_DIAMPU_FAILED"

const GET_LIST_SKP_START = "GET_LIST_SKP_START"
const GET_LIST_SKP_SUCCESS = "GET_LIST_SKP_SUCCESS"
const GET_LIST_SKP_FAILED = "GET_LIST_SKP_FAILED"

const CREATE_SKP_START = "CREATE_SKP_START"
const CREATE_SKP_SUCCESS = "CREATE_SKP_SUCCESS"
const CREATE_SKP_FAILED = "CREATE_SKP_FAILED"

const UPDATE_SKP_START = "UPDATE_SKP_START"
const UPDATE_SKP_SUCCESS = "UPDATE_SKP_SUCCESS"
const UPDATE_SKP_FAILED = "UPDATE_SKP_FAILED"

const DELETE_SKP_START = "DELETE_SKP_START"
const DELETE_SKP_SUCCESS = "DELETE_SKP_SUCCESS"
const DELETE_SKP_FAILED = "DELETE_SKP_FAILED"

const GET_INDIKATOR_SKP_START = "GET_INDIKATOR_SKP_START"
const GET_INDIKATOR_SKP_SUCCESS = "GET_INDIKATOR_SKP_SUCCESS"
const GET_INDIKATOR_SKP_FAILED = "GET_INDIKATOR_SKP_FAILED"

const GET_LIST_RENCANA_AKSI_START = "GET_LIST_RENCANA_AKSI_START"
const GET_LIST_RENCANA_AKSI_SUCCESS = "GET_LIST_RENCANA_AKSI_SUCCESS"
const GET_LIST_RENCANA_AKSI_FAILED = "GET_LIST_RENCANA_AKSI_FAILED"

const CREATE_RENCANA_AKSI_START = "CREATE_RENCANA_AKSI_START"
const CREATE_RENCANA_AKSI_SUCCESS = "CREATE_RENCANA_AKSI_SUCCESS"
const CREATE_RENCANA_AKSI_FAILED = "CREATE_RENCANA_AKSI_FAILED"

const UPDATE_RENCANA_AKSI_START = "UPDATE_RENCANA_AKSI_START"
const UPDATE_RENCANA_AKSI_SUCCESS = "UPDATE_RENCANA_AKSI_SUCCESS"
const UPDATE_RENCANA_AKSI_FAILED = "UPDATE_RENCANA_AKSI_FAILED"

const DELETE_RENCANA_AKSI_START = "DELETE_RENCANA_AKSI_START"   
const DELETE_RENCANA_AKSI_SUCCESS = "DELETE_RENCANA_AKSI_SUCCESS"
const DELETE_RENCANA_AKSI_FAILED = "DELETE_RENCANA_AKSI_FAILED"

const GET_LIST_REALISASI_SKP_START = "GET_LIST_REALISASI_SKP_START"
const GET_LIST_REALISASI_SKP_SUCCESS = "GET_LIST_REALISASI_SKP_SUCCESS"
const GET_LIST_REALISASI_SKP_FAILED = "GET_LIST_REALISASI_SKP_FAILED"

const UPDATE_REALISASI_SKP_START = "UPDATE_REALISASI_SKP_START"
const UPDATE_REALISASI_SKP_SUCCESS = "UPDATE_REALISASI_SKP_SUCCESS"
const UPDATE_REALISASI_SKP_FAILED = "UPDATE_REALISASI_SKP_FAILED"

const GET_LIST_RENCANA_AKSI_REALISASI_START = "GET_LIST_RENCANA_AKSI_REALISASI_START"
const GET_LIST_RENCANA_AKSI_REALISASI_SUCCESS = "GET_LIST_RENCANA_AKSI_REALISASI_SUCCESS"
const GET_LIST_RENCANA_AKSI_REALISASI_FAILED = "GET_LIST_RENCANA_AKSI_REALISASI_FAILED"

const UPDATE_RENCANA_AKSI_REALISASI_START = "UPDATE_RENCANA_AKSI_REALISASI_START"
const UPDATE_RENCANA_AKSI_REALISASI_SUCCESS = "UPDATE_RENCANA_AKSI_REALISASI_SUCCESS"
const UPDATE_RENCANA_AKSI_REALISASI_FAILED = "UPDATE_RENCANA_AKSI_REALISASI_FAILED"

export {
    GET_LIST_PERIODE_SKP_START,
    GET_LIST_PERIODE_SKP_SUCCESS,
    GET_LIST_PERIODE_SKP_FAILED,

    GET_PERIODE_SKP_START,
    GET_PERIODE_SKP_SUCCESS,
    GET_PERIODE_SKP_FAILED,

    CREATE_PERIODE_SKP_START,
    CREATE_PERIODE_SKP_SUCCESS,
    CREATE_PERIODE_SKP_FAILED,

    GET_LIST_SASARAN_YANG_DIAMPU_START,
    GET_LIST_SASARAN_YANG_DIAMPU_SUCCESS,
    GET_LIST_SASARAN_YANG_DIAMPU_FAILED,

    GET_LIST_SKP_START,
    GET_LIST_SKP_SUCCESS,
    GET_LIST_SKP_FAILED,

    CREATE_SKP_START,
    CREATE_SKP_SUCCESS,
    CREATE_SKP_FAILED,

    UPDATE_SKP_START,
    UPDATE_SKP_SUCCESS,
    UPDATE_SKP_FAILED,

    DELETE_SKP_START,
    DELETE_SKP_SUCCESS,
    DELETE_SKP_FAILED,

    GET_INDIKATOR_SKP_START,
    GET_INDIKATOR_SKP_SUCCESS,
    GET_INDIKATOR_SKP_FAILED,

    GET_LIST_RENCANA_AKSI_START,
    GET_LIST_RENCANA_AKSI_SUCCESS,
    GET_LIST_RENCANA_AKSI_FAILED,

    CREATE_RENCANA_AKSI_START,
    CREATE_RENCANA_AKSI_SUCCESS,
    CREATE_RENCANA_AKSI_FAILED,

    UPDATE_RENCANA_AKSI_START,
    UPDATE_RENCANA_AKSI_SUCCESS,
    UPDATE_RENCANA_AKSI_FAILED,

    DELETE_RENCANA_AKSI_START,
    DELETE_RENCANA_AKSI_SUCCESS,
    DELETE_RENCANA_AKSI_FAILED,

    GET_LIST_REALISASI_SKP_START,
    GET_LIST_REALISASI_SKP_SUCCESS,
    GET_LIST_REALISASI_SKP_FAILED,

    UPDATE_REALISASI_SKP_START,
    UPDATE_REALISASI_SKP_SUCCESS,
    UPDATE_REALISASI_SKP_FAILED,

    GET_LIST_RENCANA_AKSI_REALISASI_START,
    GET_LIST_RENCANA_AKSI_REALISASI_SUCCESS,
    GET_LIST_RENCANA_AKSI_REALISASI_FAILED,

    UPDATE_RENCANA_AKSI_REALISASI_START,
    UPDATE_RENCANA_AKSI_REALISASI_SUCCESS,
    UPDATE_RENCANA_AKSI_REALISASI_FAILED,
}