const GET_LIST_SASARANDIAMPU_OPD_START = "GET_LIST_SASARANDIAMPU_OPD_START"
const GET_LIST_SASARANDIAMPU_OPD_SUCCESS = "GET_LIST_SASARANDIAMPU_OPD_SUCCESS"
const GET_LIST_SASARANDIAMPU_OPD_FAILED = "GET_LIST_SASARANDIAMPU_OPD_FAILED"

const GET_LIST_TUJUANOPD_START = "GET_LIST_TUJUANOPD_START"
const GET_LIST_TUJUANOPD_SUCCESS = "GET_LIST_TUJUANOPD_SUCCESS"
const GET_LIST_TUJUANOPD_FAILED = "GET_LIST_TUJUANOPD_FAILED"

const CREATE_TUJUANOPD_START = "CREATE_TUJUANOPD_START"
const CREATE_TUJUANOPD_SUCCESS = "CREATE_TUJUANOPD_SUCCESS"
const CREATE_TUJUANOPD_FAILED = "CREATE_TUJUANOPD_FAILED"

const GET_TUJUANOPD_START = "GET_TUJUANOPD_START"
const GET_TUJUANOPD_SUCCESS = "GET_TUJUANOPD_SUCCESS"
const GET_TUJUANOPD_FAILED = "GET_TUJUANOPD_FAILED"

const UPDATE_TUJUANOPD_START = "UPDATE_TUJUANOPD_START"
const UPDATE_TUJUANOPD_SUCCESS = "UPDATE_TUJUANOPD_SUCCESS"
const UPDATE_TUJUANOPD_FAILED = "UPDATE_TUJUANOPD_FAILED"

const DELETE_TUJUANOPD_START = "DELETE_TUJUANOPD_START"
const DELETE_TUJUANOPD_SUCCESS = "DELETE_TUJUANOPD_SUCCESS"
const DELETE_TUJUANOPD_FAILED = "DELETE_TUJUANOPD_FAILED"

export {
    GET_LIST_SASARANDIAMPU_OPD_START,
    GET_LIST_SASARANDIAMPU_OPD_SUCCESS,
    GET_LIST_SASARANDIAMPU_OPD_FAILED,

    GET_LIST_TUJUANOPD_START,
    GET_LIST_TUJUANOPD_SUCCESS,
    GET_LIST_TUJUANOPD_FAILED,

    CREATE_TUJUANOPD_START,
    CREATE_TUJUANOPD_SUCCESS,
    CREATE_TUJUANOPD_FAILED,

    GET_TUJUANOPD_START,
    GET_TUJUANOPD_SUCCESS,
    GET_TUJUANOPD_FAILED,

    UPDATE_TUJUANOPD_START,
    UPDATE_TUJUANOPD_SUCCESS,
    UPDATE_TUJUANOPD_FAILED,

    DELETE_TUJUANOPD_START,
    DELETE_TUJUANOPD_SUCCESS,
    DELETE_TUJUANOPD_FAILED
}