const GET_LIST_SASARANKDH_START        = "GET_LIST_SASARANKDH_START"
const GET_LIST_SASARANKDH_SUCCESS      = "GET_LIST_SASARANKDH_SUCCESS"
const GET_LIST_SASARANKDH_FAILED       = "GET_LIST_SASARANKDH_FAILED"

const CREATE_SASARANKDH_START          = "CREATE_SASARANKDH_START"
const CREATE_SASARANKDH_SUCCESS        = "CREATE_SASARANKDH_SUCCESS"
const CREATE_SASARANKDH_FAILED         = "CREATE_SASARANKDH_FAILED"

const GET_SASARANKDH_START             = "GET_SASARANKDH_START"
const GET_SASARANKDH_SUCCESS           = "GET_SASARANKDH_SUCCESS"
const GET_SASARANKDH_FAILED            = "GET_SASARANKDH_FAILED"

const UPDATE_SASARANKDH_START          = "UPDATE_SASARANKDH_START"
const UPDATE_SASARANKDH_SUCCESS        = "UPDATE_SASARANKDH_SUCCESS"
const UPDATE_SASARANKDH_FAILED         = "UPDATE_SASARANKDH_FAILED"

const DELETE_SASARANKDH_START          = "DELETE_SASARANKDH_START"
const DELETE_SASARANKDH_SUCCESS        = "DELETE_SASARANKDH_SUCCESS"
const DELETE_SASARANKDH_FAILED         = "DELETE_SASARANKDH_FAILED"

export {
    GET_LIST_SASARANKDH_START, GET_LIST_SASARANKDH_SUCCESS, GET_LIST_SASARANKDH_FAILED,
    CREATE_SASARANKDH_START, CREATE_SASARANKDH_SUCCESS, CREATE_SASARANKDH_FAILED,
    GET_SASARANKDH_START, GET_SASARANKDH_SUCCESS, GET_SASARANKDH_FAILED,
    UPDATE_SASARANKDH_START, UPDATE_SASARANKDH_SUCCESS, UPDATE_SASARANKDH_FAILED,
    DELETE_SASARANKDH_START, DELETE_SASARANKDH_SUCCESS, DELETE_SASARANKDH_FAILED
}