const GET_LIST_SASARANOPD_START = "GET_LIST_SASARANOPD_START"
const GET_LIST_SASARANOPD_SUCCESS = "GET_LIST_SASARANOPD_SUCCESS"
const GET_LIST_SASARANOPD_FAILED = "GET_LIST_SASARANOPD_FAILED"

const GET_REF_SASARANOPD_START = "GET_REF_SASARANOPD_START"
const GET_REF_SASARANOPD_SUCCESS = "GET_REF_SASARANOPD_SUCCESS"
const GET_REF_SASARANOPD_FAILED = "GET_REF_SASARANOPD_FAILED"

const CREATE_SASARANOPD_START = "CREATE_SASARANOPD_START"
const CREATE_SASARANOPD_SUCCESS = "CREATE_SASARANOPD_SUCCESS"
const CREATE_SASARANOPD_FAILED = "CREATE_SASARANOPD_FAILED"

const GET_SASARANOPD_START = "GET_SASARANOPD_START"
const GET_SASARANOPD_SUCCESS = "GET_SASARANOPD_SUCCESS"
const GET_SASARANOPD_FAILED = "GET_SASARANOPD_FAILED"

const UPDATE_SASARANOPD_START = "UPDATE_SASARANOPD_START"
const UPDATE_SASARANOPD_SUCCESS = "UPDATE_SASARANOPD_SUCCESS"
const UPDATE_SASARANOPD_FAILED = "UPDATE_SASARANOPD_FAILED"

const DELETE_SASARANOPD_START = "DELETE_SASARANOPD_START"
const DELETE_SASARANOPD_SUCCESS = "DELETE_SASARANOPD_SUCCESS"
const DELETE_SASARANOPD_FAILED = "DELETE_SASARANOPD_FAILED"

export {
    GET_REF_SASARANOPD_START,
    GET_REF_SASARANOPD_SUCCESS,
    GET_REF_SASARANOPD_FAILED,

    GET_LIST_SASARANOPD_START,
    GET_LIST_SASARANOPD_SUCCESS,
    GET_LIST_SASARANOPD_FAILED,

    CREATE_SASARANOPD_START,
    CREATE_SASARANOPD_SUCCESS,
    CREATE_SASARANOPD_FAILED,

    GET_SASARANOPD_START,
    GET_SASARANOPD_SUCCESS,
    GET_SASARANOPD_FAILED,

    UPDATE_SASARANOPD_START,
    UPDATE_SASARANOPD_SUCCESS,
    UPDATE_SASARANOPD_FAILED,

    DELETE_SASARANOPD_START,
    DELETE_SASARANOPD_SUCCESS,
    DELETE_SASARANOPD_FAILED
}