const GET_LIST_PKOPD_START = "GET_LIST_PKOPD_START"
const GET_LIST_PKOPD_SUCCESS = "GET_LIST_PKOPD_SUCCESS"
const GET_LIST_PKOPD_FAILED = "GET_LIST_PKOPD_FAILED"

const CREATE_PKOPD_START = "CREATE_PKOPD_START"
const CREATE_PKOPD_SUCCESS = "CREATE_PKOPD_SUCCESS"
const CREATE_PKOPD_FAILED = "CREATE_PKOPD_FAILED"

const CREATE_PROGRAM_PKOPD_START = "CREATE_PROGRAM_PKOPD_START"
const CREATE_PROGRAM_PKOPD_SUCCESS = "CREATE_PROGRAM_PKOPD_SUCCESS"
const CREATE_PROGRAM_PKOPD_FAILED = "CREATE_PROGRAM_PKOPD_FAILED"

const GET_LIST_PROGRAM_PKOPD_START = "GET_LIST_PROGRAM_PKOPD_START"
const GET_LIST_PROGRAM_PKOPD_SUCCESS = "GET_LIST_PROGRAM_PKOPD_SUCCESS"
const GET_LIST_PROGRAM_PKOPD_FAILED = "GET_LIST_PROGRAM_PKOPD_FAILED"

export {
    GET_LIST_PKOPD_START,
    GET_LIST_PKOPD_SUCCESS,
    GET_LIST_PKOPD_FAILED,

    CREATE_PKOPD_START,
    CREATE_PKOPD_SUCCESS,
    CREATE_PKOPD_FAILED,

    CREATE_PROGRAM_PKOPD_START,
    CREATE_PROGRAM_PKOPD_SUCCESS,
    CREATE_PROGRAM_PKOPD_FAILED,

    GET_LIST_PROGRAM_PKOPD_START,
    GET_LIST_PROGRAM_PKOPD_SUCCESS,
    GET_LIST_PROGRAM_PKOPD_FAILED
}