const GET_LIST_RENSTRA_OPD_START = "GET_LIST_RENSTRA_OPD_START"
const GET_LIST_RENSTRA_OPD_SUCCESS = "GET_LIST_RENSTRA_OPD_SUCCESS"
const GET_LIST_RENSTRA_OPD_FAILED = "GET_LIST_RENSTRA_OPD_FAILED"

const CREATE_TARGET_RENSTRA_OPD_START = "CREATE_TARGET_RENSTRA_OPD_START"
const CREATE_TARGET_RENSTRA_OPD_SUCCESS = "CREATE_TARGET_RENSTRA_OPD_SUCCESS"
const CREATE_TARGET_RENSTRA_OPD_FAILED = "CREATE_TARGET_RENSTRA_OPD_FAILED"

export {
    GET_LIST_RENSTRA_OPD_START,
    GET_LIST_RENSTRA_OPD_SUCCESS,
    GET_LIST_RENSTRA_OPD_FAILED,

    CREATE_TARGET_RENSTRA_OPD_START,
    CREATE_TARGET_RENSTRA_OPD_SUCCESS,
    CREATE_TARGET_RENSTRA_OPD_FAILED
}