const GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_START = "GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_START"
const GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_SUCCESS = "GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_SUCCESS"
const GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_FAILED = "GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_FAILED"

const GET_LIST_PENGAMPUINDIKATOR_START = "GET_LIST_PENGAMPUINDIKATOR_START"
const GET_LIST_PENGAMPUINDIKATOR_SUCCESS = "GET_LIST_PENGAMPUINDIKATOR_SUCCESS"
const GET_LIST_PENGAMPUINDIKATOR_FAILED = "GET_LIST_PENGAMPUINDIKATOR_FAILED"

const CREATE_PENGAMPUINDIKATOR_START = "CREATE_PENGAMPUINDIKATOR_START"
const CREATE_PENGAMPUINDIKATOR_SUCCESS = "CREATE_PENGAMPUINDIKATOR_SUCCESS"
const CREATE_PENGAMPUINDIKATOR_FAILED = "CREATE_PENGAMPUINDIKATOR_FAILED"

const UPDATE_PENGAMPUINDIKATOR_START = "UPDATE_PENGAMPUINDIKATOR_START"
const UPDATE_PENGAMPUINDIKATOR_SUCCESS = "UPDATE_PENGAMPUINDIKATOR_SUCCESS"
const UPDATE_PENGAMPUINDIKATOR_FAILED = "UPDATE_PENGAMPUINDIKATOR_FAILED"

const DELETE_PENGAMPUINDIKATOR_START = "DELETE_PENGAMPUINDIKATOR_START"
const DELETE_PENGAMPUINDIKATOR_SUCCESS = "DELETE_PENGAMPUINDIKATOR_SUCCESS"
const DELETE_PENGAMPUINDIKATOR_FAILED = "DELETE_PENGAMPUINDIKATOR_FAILED"

export {
    GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_START,
    GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_SUCCESS,
    GET_LIST_PEGAWAI_PENGAMPUINDIKATOR_FAILED,

    GET_LIST_PENGAMPUINDIKATOR_START,
    GET_LIST_PENGAMPUINDIKATOR_SUCCESS,
    GET_LIST_PENGAMPUINDIKATOR_FAILED,

    CREATE_PENGAMPUINDIKATOR_START,
    CREATE_PENGAMPUINDIKATOR_SUCCESS,
    CREATE_PENGAMPUINDIKATOR_FAILED,

    UPDATE_PENGAMPUINDIKATOR_START,
    UPDATE_PENGAMPUINDIKATOR_SUCCESS,
    UPDATE_PENGAMPUINDIKATOR_FAILED,

    DELETE_PENGAMPUINDIKATOR_START,
    DELETE_PENGAMPUINDIKATOR_SUCCESS,
    DELETE_PENGAMPUINDIKATOR_FAILED
}