const GET_LIST_CASCADINGKDH_START = "GET_LIST_CASCADINGKDH_START"
const GET_LIST_CASCADINGKDH_SUCCESS = "GET_LIST_CASCADINGKDH_SUCCESS"
const GET_LIST_CASCADINGKDH_FAILED = "GET_LIST_CASCADINGKDH_FAILED"

const CREATE_CASCADINGKDH_START = "CREATE_CASCADINGKDH_START"
const CREATE_CASCADINGKDH_SUCCESS = "CREATE_CASCADINGKDH_SUCCESS"
const CREATE_CASCADINGKDH_FAILED = "CREATE_CASCADINGKDH_FAILED"

export {
    GET_LIST_CASCADINGKDH_START,
    GET_LIST_CASCADINGKDH_SUCCESS,
    GET_LIST_CASCADINGKDH_FAILED,

    CREATE_CASCADINGKDH_START,
    CREATE_CASCADINGKDH_SUCCESS,
    CREATE_CASCADINGKDH_FAILED
}