const GET_LIST_TUJUANKDH_START        = "GET_LIST_TUJUANKDH_START"
const GET_LIST_TUJUANKDH_SUCCESS      = "GET_LIST_TUJUANKDH_SUCCESS"
const GET_LIST_TUJUANKDH_FAILED       = "GET_LIST_TUJUANKDH_FAILED"

const CREATE_TUJUANKDH_START          = "CREATE_TUJUANKDH_START"
const CREATE_TUJUANKDH_SUCCESS        = "CREATE_TUJUANKDH_SUCCESS"
const CREATE_TUJUANKDH_FAILED         = "CREATE_TUJUANKDH_FAILED"

const GET_TUJUANKDH_START             = "GET_TUJUANKDH_START"
const GET_TUJUANKDH_SUCCESS           = "GET_TUJUANKDH_SUCCESS"
const GET_TUJUANKDH_FAILED            = "GET_TUJUANKDH_FAILED"

const UPDATE_TUJUANKDH_START          = "UPDATE_TUJUANKDH_START"
const UPDATE_TUJUANKDH_SUCCESS        = "UPDATE_TUJUANKDH_SUCCESS"
const UPDATE_TUJUANKDH_FAILED         = "UPDATE_TUJUANKDH_FAILED"

const DELETE_TUJUANKDH_START          = "DELETE_TUJUANKDH_START"
const DELETE_TUJUANKDH_SUCCESS        = "DELETE_TUJUANKDH_SUCCESS"
const DELETE_TUJUANKDH_FAILED         = "DELETE_TUJUANKDH_FAILED"

export {
    GET_LIST_TUJUANKDH_START, GET_LIST_TUJUANKDH_SUCCESS, GET_LIST_TUJUANKDH_FAILED,
    CREATE_TUJUANKDH_START, CREATE_TUJUANKDH_SUCCESS, CREATE_TUJUANKDH_FAILED,
    GET_TUJUANKDH_START, GET_TUJUANKDH_SUCCESS, GET_TUJUANKDH_FAILED,
    UPDATE_TUJUANKDH_START, UPDATE_TUJUANKDH_SUCCESS, UPDATE_TUJUANKDH_FAILED,
    DELETE_TUJUANKDH_START, DELETE_TUJUANKDH_SUCCESS, DELETE_TUJUANKDH_FAILED
}